Check for null returned from canvas.getContext
tensorflow/tfjs pull request #3970
Opened 2020-09-24 18:10 UTC by jameshfisher

getWebGLRenderingContext can clearly return null.
This is expected behavior, because canvas.getContext can return null.
We therefore must check for null before trying to call .isContextLost on it.

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

2020-09-24 18:11 UTC, jameshfisher commented
For further context, see https://github.com/tensorflow/tfjs/pull/3969

2020-09-29 11:40 UTC, annxingyuan commented on tfjs-backend-webgl/src/canvas_util.ts
> +    if (newCtx) {
newCtx != null

2020-09-29 11:40 UTC, annxingyuan requested changes
Thanks @jameshfisher ! Just left a small comment.

2020-09-29 13:24 UTC, annxingyuan approved these changes

2020-10-01 11:25 UTC, merged