[webgl] Custom mean kernel.
tensorflow/tfjs pull request #4033
Opened 2020-10-07 15:27 UTC by annxingyuan

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

2020-10-08 13:33 UTC, annxingyuan commented
Hi @pyu10055 - FYI I've verified this fix with my iPhone on the DDSP demo.

2020-10-08 13:34 UTC, annxingyuan commented
Hi @tafsiri - this PR is mostly about a precision issue in WebGL that Ping's been facing, but was also hoping to get your feedback on the modularization bit.

2020-10-09 01:00 UTC, pyu10055 requested changes
Thanks for refactoring this, a high level question on multiple reduction stages, please take a look at the comments below.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4033#-:-MJ9rePD0oT4WMh2LHcR:b-1zprhv)* status: 0 of 1 approvals obtained (waiting on @annxingyuan, @pyu10055, and @tafsiri)

___
*[tfjs-backend-webgl/src/mean_gpu.ts, line 3 at r2](https://reviewable.io/reviews/tensorflow/tfjs/4033#-MJ9nHbV9NVD7eUcGcSb:-MJ9nHbW1XUhmKzlbVeO:bb6ht35) ([raw file](https://github.com/tensorflow/tfjs/blob/eecb01fc6a7d2b82a1e9570b8e60f2b6b6e5980f/tfjs-backend-webgl/src/mean_gpu.ts#L3)):*
> ```XML
> /**
>  * @license
>  * Copyright 2017 Google LLC. All Rights Reserved.
> ```

2020
___
*[tfjs-backend-webgl/src/mean_gpu.ts, line 36 at r2](https://reviewable.io/reviews/tensorflow/tfjs/4033#-MJ9qTza4MgvlYEBUiP5:-MJ9qTza4MgvlYEBUiP6:bmn7rq) ([raw file](https://github.com/tensorflow/tfjs/blob/eecb01fc6a7d2b82a1e9570b8e60f2b6b6e5980f/tfjs-backend-webgl/src/mean_gpu.ts#L36)):*
> ```XML
>     if (divisor != null) {
>       updateSnippet =
>           `sumValue += dot(values * ${(1 / divisor).toPrecision(8)}, ones);`;
> ```

why it need to limit to precision 8?
___
*[tfjs-backend-webgl/src/kernels/Mean_impl.ts, line 27 at r2](https://reviewable.io/reviews/tensorflow/tfjs/4033#-MJ9rGWl5pC9YHxPgC1g:-MJ9rGWl5pC9YHxPgC1h:b-lqt1mi) ([raw file](https://github.com/tensorflow/tfjs/blob/eecb01fc6a7d2b82a1e9570b8e60f2b6b6e5980f/tfjs-backend-webgl/src/kernels/Mean_impl.ts#L27)):*
> ```XML
> function meanReduce(
>     x: TensorInfo, reduceSize: number, backend: MathBackendWebGL): TensorInfo {
>   const reductionStages = getReductionStages(x.shape);
> ```

Why this still need multiple reduction stages if the divisor can passed in to the mean program?
If the calculation is done with float32 within the shader, there should be not precision problem of float16, right?


<!-- Sent from Reviewable.io -->

2020-10-09 09:25 UTC, annxingyuan reviewed
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4033)* status: 0 of 1 approvals obtained (waiting on @pyu10055 and @tafsiri)

___
*[tfjs-backend-webgl/src/mean_gpu.ts, line 3 at r2](https://reviewable.io/reviews/tensorflow/tfjs/4033#-MJ9nHbV9NVD7eUcGcSb:-MJBdrQwAjpcXetWbpqU:bb6un1j) ([raw file](https://github.com/tensorflow/tfjs/blob/eecb01fc6a7d2b82a1e9570b8e60f2b6b6e5980f/tfjs-backend-webgl/src/mean_gpu.ts#L3)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

2020
</blockquote></details>

Done
___
*[tfjs-backend-webgl/src/mean_gpu.ts, line 36 at r2](https://reviewable.io/reviews/tensorflow/tfjs/4033#-MJ9qTza4MgvlYEBUiP5:-MJBe4J_E4WnM-XSuA8j:bb6un1j) ([raw file](https://github.com/tensorflow/tfjs/blob/eecb01fc6a7d2b82a1e9570b8e60f2b6b6e5980f/tfjs-backend-webgl/src/mean_gpu.ts#L36)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

why it need to limit to precision 8?
</blockquote></details>

Done
___
*[tfjs-backend-webgl/src/kernels/Mean_impl.ts, line 27 at r2](https://reviewable.io/reviews/tensorflow/tfjs/4033#-MJ9rGWl5pC9YHxPgC1g:-MJBeA4w3uTuEEgvnWdK:bpda7t3) ([raw file](https://github.com/tensorflow/tfjs/blob/eecb01fc6a7d2b82a1e9570b8e60f2b6b6e5980f/tfjs-backend-webgl/src/kernels/Mean_impl.ts#L27)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

Why this still need multiple reduction stages if the divisor can passed in to the mean program?
If the calculation is done with float32 within the shader, there should be not precision problem of float16, right?
</blockquote></details>

Currently mean goes through a div kernel and then a sum kernel, and the sum kernel requires one or more passes (like other reduction ops - max, min, prod, etc.). This PR fuses div into the first pass of the sum kernel, but we still may need multiple passes in order to finish computing sum. 


<!-- Sent from Reviewable.io -->

2020-10-09 14:40 UTC, pyu10055 requested changes
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4033)* status: 0 of 1 approvals obtained (waiting on @annxingyuan, @pyu10055, and @tafsiri)

___
*[tfjs-backend-webgl/src/kernels/Mean_impl.ts, line 27 at r2](https://reviewable.io/reviews/tensorflow/tfjs/4033#-MJ9rGWl5pC9YHxPgC1g:-MJCnRhvB28qVk12aubW:bqsaoeg) ([raw file](https://github.com/tensorflow/tfjs/blob/eecb01fc6a7d2b82a1e9570b8e60f2b6b6e5980f/tfjs-backend-webgl/src/kernels/Mean_impl.ts#L27)):*
<details><summary><i>Previously, annxingyuan (Ann Yuan) wrote…</i></summary><blockquote>

Currently mean goes through a div kernel and then a sum kernel, and the sum kernel requires one or more passes (like other reduction ops - max, min, prod, etc.). This PR fuses div into the first pass of the sum kernel, but we still may need multiple passes in order to finish computing sum. 
</blockquote></details>

I see, will it be possible to merge mean as an operation for ReduceProgram?


<!-- Sent from Reviewable.io -->

2020-10-09 14:44 UTC, annxingyuan reviewed
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4033)* status: 0 of 1 approvals obtained (waiting on @pyu10055 and @tafsiri)

___
*[tfjs-backend-webgl/src/kernels/Mean_impl.ts, line 27 at r2](https://reviewable.io/reviews/tensorflow/tfjs/4033#-MJ9rGWl5pC9YHxPgC1g:-MJCnvEgEqkLEplVLw9E:b-bvtzbl) ([raw file](https://github.com/tensorflow/tfjs/blob/eecb01fc6a7d2b82a1e9570b8e60f2b6b6e5980f/tfjs-backend-webgl/src/kernels/Mean_impl.ts#L27)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

I see, will it be possible to merge mean as an operation for ReduceProgram?
</blockquote></details>

This PR treats mean as a reduction - the new MeanProgram works the same way as ReduceProgram with 'sum' - the only difference is that MeanProgram fuses div in the first pass. Is that what you mean by merge mean as an operation for ReduceProgram?


<!-- Sent from Reviewable.io -->

2020-10-09 15:14 UTC, tafsiri reviewed
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4033)* status: 0 of 1 approvals obtained (waiting on @annxingyuan, @pyu10055, and @tafsiri)

___
*[tfjs-backend-webgl/src/kernels/Mean_impl.ts, line 40 at r3](https://reviewable.io/reviews/tensorflow/tfjs/4033#-MJCuoZf84uVkxABhl2n:-MJCuoZf84uVkxABhl2o:b1zxfe0) ([raw file](https://github.com/tensorflow/tfjs/blob/12fa219db008423714c08abfa86c5dd90e0dfb1a/tfjs-backend-webgl/src/kernels/Mean_impl.ts#L40)):*
> ```XML
>     result = backend.runWebGLProgram(program, [result], 'float32');
> 
>     if (previousResult.dataId !== x.dataId) {
> ```

from a modularization perspective I was just wondering when this would be false? from what i can tell backend.runWebGLProgram will always make a new dataId/TensorInfo. 


<!-- Sent from Reviewable.io -->

2020-10-09 15:25 UTC, tafsiri reviewed
> Reviewed 1 of 6 files at r1, 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4033)* status: 0 of 1 approvals obtained (waiting on @annxingyuan, @pyu10055, and @tafsiri)

___
*[tfjs-backend-webgl/src/kernels/Mean.ts, line 77 at r3](https://reviewable.io/reviews/tensorflow/tfjs/4033#-MJCwAzP7aFpawCC_1ha:-MJCwAzQAFrXFsYRXMf2:by2pl2) ([raw file](https://github.com/tensorflow/tfjs/blob/12fa219db008423714c08abfa86c5dd90e0dfb1a/tfjs-backend-webgl/src/kernels/Mean.ts#L77)):*
> ```XML
> 
>     if (meanInputIsTransposed) {
>       webglBackend.disposeIntermediateTensorInfo(meanInput);
> ```

A code style suggestion, how would you feel about asserting meanInput !== x before disposing meanInput (here and in other places where a variable that is going to be disposed is at somepoint pointing to an input tensorInfo. The code you have here is correct, but since we don't generally test for accidentally disposing inputs, an assertion would guard against any change that resulted in meanInput not being reassigned when meanInputIsTransposed is true.

An alternative pattern, which I used here (https://github.com/tensorflow/tfjs/pull/4042/files#diff-e793ca80e577c3a0d5304d61e9cd957aR47) is to make an array of tensorInfos you want to dispose at the end and, inside the meanInputIsTransposed block, push the newly created tensorinfo into that array, then you can dispose it at the end. I found its also a handy pattern for dealing with multiple conditions under which tensorinfos might get disposed (not the situation you have here). 


<!-- Sent from Reviewable.io -->

2020-10-12 13:45 UTC, annxingyuan reviewed
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4033)* status: 0 of 1 approvals obtained (waiting on @pyu10055 and @tafsiri)

___
*[tfjs-backend-webgl/src/kernels/Mean.ts, line 77 at r3](https://reviewable.io/reviews/tensorflow/tfjs/4033#-MJCwAzP7aFpawCC_1ha:-MJRxqUK9NGGMNvcjvaZ:b9b00c0) ([raw file](https://github.com/tensorflow/tfjs/blob/12fa219db008423714c08abfa86c5dd90e0dfb1a/tfjs-backend-webgl/src/kernels/Mean.ts#L77)):*
<details><summary><i>Previously, tafsiri (Yannick Assogba) wrote…</i></summary><blockquote>

A code style suggestion, how would you feel about asserting meanInput !== x before disposing meanInput (here and in other places where a variable that is going to be disposed is at somepoint pointing to an input tensorInfo. The code you have here is correct, but since we don't generally test for accidentally disposing inputs, an assertion would guard against any change that resulted in meanInput not being reassigned when meanInputIsTransposed is true.

An alternative pattern, which I used here (https://github.com/tensorflow/tfjs/pull/4042/files#diff-e793ca80e577c3a0d5304d61e9cd957aR47) is to make an array of tensorInfos you want to dispose at the end and, inside the meanInputIsTransposed block, push the newly created tensorinfo into that array, then you can dispose it at the end. I found its also a handy pattern for dealing with multiple conditions under which tensorinfos might get disposed (not the situation you have here). 


</blockquote></details>

Done

great idea!
___
*[tfjs-backend-webgl/src/kernels/Mean_impl.ts, line 27 at r2](https://reviewable.io/reviews/tensorflow/tfjs/4033#-MJ9rGWl5pC9YHxPgC1g:-MJS2jCF4HBFMIvnnsLn:b-j6q8po) ([raw file](https://github.com/tensorflow/tfjs/blob/eecb01fc6a7d2b82a1e9570b8e60f2b6b6e5980f/tfjs-backend-webgl/src/kernels/Mean_impl.ts#L27)):*
<details><summary><i>Previously, annxingyuan (Ann Yuan) wrote…</i></summary><blockquote>

This PR treats mean as a reduction - the new MeanProgram works the same way as ReduceProgram with 'sum' - the only difference is that MeanProgram fuses div in the first pass. Is that what you mean by merge mean as an operation for ReduceProgram?
</blockquote></details>

Done

I refactored this per our offline discussion - let me know if this is what you had in mind.
___
*[tfjs-backend-webgl/src/kernels/Mean_impl.ts, line 40 at r3](https://reviewable.io/reviews/tensorflow/tfjs/4033#-MJCuoZf84uVkxABhl2n:-MJRyU_498I9a0WJh9IN:bexi3z6) ([raw file](https://github.com/tensorflow/tfjs/blob/12fa219db008423714c08abfa86c5dd90e0dfb1a/tfjs-backend-webgl/src/kernels/Mean_impl.ts#L40)):*
<details><summary><i>Previously, tafsiri (Yannick Assogba) wrote…</i></summary><blockquote>

from a modularization perspective I was just wondering when this would be false? from what i can tell backend.runWebGLProgram will always make a new dataId/TensorInfo. 
</blockquote></details>

That's true, but previousResult is assigned to result before we call runWebGLProgram, so the first run through this loop previousResult equals x.


<!-- Sent from Reviewable.io -->

2020-10-12 16:23 UTC, pyu10055 approved these changes
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4033)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @annxingyuan and @tafsiri)

___
*[tfjs-backend-webgl/src/kernels/Mean_impl.ts, line 27 at r2](https://reviewable.io/reviews/tensorflow/tfjs/4033#-MJ9rGWl5pC9YHxPgC1g:-MJSbJ1478uhnpV6q0py:b-4ufyam) ([raw file](https://github.com/tensorflow/tfjs/blob/eecb01fc6a7d2b82a1e9570b8e60f2b6b6e5980f/tfjs-backend-webgl/src/kernels/Mean_impl.ts#L27)):*
<details><summary><i>Previously, annxingyuan (Ann Yuan) wrote…</i></summary><blockquote>

Done

I refactored this per our offline discussion - let me know if this is what you had in mind.
</blockquote></details>

Nice, Thanks!
___
*[tfjs-core/src/ops/mean_test.ts, line 22 at r4](https://reviewable.io/reviews/tensorflow/tfjs/4033#-MJSbrqx2MuWumXzYFt_:-MJSbrqx2MuWumXzYFta:bw74k4f) ([raw file](https://github.com/tensorflow/tfjs/blob/4eb81c74fc656fb7f7724f534cb08fc2c0e954c1/tfjs-core/src/ops/mean_test.ts#L22)):*
> ```XML
> import {expectArraysClose, expectArraysEqual} from '../test_util';
> 
> describeWithFlags('mean', ALL_ENVS, () => {
> ```

can you add a test that covers the large reduction dimension?


<!-- Sent from Reviewable.io -->

2020-10-12 18:25 UTC, annxingyuan reviewed
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4033)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @annxingyuan, @pyu10055, and @tafsiri)

___
*[tfjs-core/src/ops/mean_test.ts, line 22 at r4](https://reviewable.io/reviews/tensorflow/tfjs/4033#-MJSbrqx2MuWumXzYFt_:-MJT2aECD9bvF7WN3hV4:bb6un1j) ([raw file](https://github.com/tensorflow/tfjs/blob/4eb81c74fc656fb7f7724f534cb08fc2c0e954c1/tfjs-core/src/ops/mean_test.ts#L22)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

can you add a test that covers the large reduction dimension?
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2020-10-12 18:29 UTC, pyu10055 requested changes
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4033)* status: 0 of 1 approvals obtained (waiting on @annxingyuan and @tafsiri)

___
*[tfjs-core/src/ops/mean_test.ts, line 22 at r4](https://reviewable.io/reviews/tensorflow/tfjs/4033#-MJSbrqx2MuWumXzYFt_:-MJT3_Wa1nfykJfcuX4r:bngkmyq) ([raw file](https://github.com/tensorflow/tfjs/blob/4eb81c74fc656fb7f7724f534cb08fc2c0e954c1/tfjs-core/src/ops/mean_test.ts#L22)):*
<details><summary><i>Previously, annxingyuan (Ann Yuan) wrote…</i></summary><blockquote>

Done
</blockquote></details>

I meant input as something like tf.ones([1, 70000])


<!-- Sent from Reviewable.io -->

2020-10-12 18:29 UTC, pyu10055 requested changes
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4033)* status: 0 of 1 approvals obtained (waiting on @annxingyuan and @tafsiri)

___
*[tfjs-core/src/ops/mean_test.ts, line 22 at r4](https://reviewable.io/reviews/tensorflow/tfjs/4033#-MJSbrqx2MuWumXzYFt_:-MJT3mnxEs4d7-bMi5Nq:b-7zmykw) ([raw file](https://github.com/tensorflow/tfjs/blob/4eb81c74fc656fb7f7724f534cb08fc2c0e954c1/tfjs-core/src/ops/mean_test.ts#L22)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

I meant input as something like tf.ones([1, 70000])
</blockquote></details>

will it be too slow for cpu?


<!-- Sent from Reviewable.io -->

2020-10-12 18:42 UTC, annxingyuan reviewed
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4033)* status: 0 of 1 approvals obtained (waiting on @annxingyuan, @pyu10055, and @tafsiri)

___
*[tfjs-core/src/ops/mean_test.ts, line 22 at r4](https://reviewable.io/reviews/tensorflow/tfjs/4033#-MJSbrqx2MuWumXzYFt_:-MJT6j550dNb-OpBEGu1:bypdcpb) ([raw file](https://github.com/tensorflow/tfjs/blob/4eb81c74fc656fb7f7724f534cb08fc2c0e954c1/tfjs-core/src/ops/mean_test.ts#L22)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

will it be too slow for cpu?
</blockquote></details>

Done

I moved the test to the webgl backend only.


<!-- Sent from Reviewable.io -->

2020-10-12 20:07 UTC, pyu10055 requested changes
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4033)* status: 0 of 1 approvals obtained (waiting on @annxingyuan and @tafsiri)

___
*[tfjs-core/src/ops/mean_test.ts, line 22 at r4](https://reviewable.io/reviews/tensorflow/tfjs/4033#-MJSbrqx2MuWumXzYFt_:-MJTPykP32nla1yrFRoX:btnam27) ([raw file](https://github.com/tensorflow/tfjs/blob/4eb81c74fc656fb7f7724f534cb08fc2c0e954c1/tfjs-core/src/ops/mean_test.ts#L22)):*
<details><summary><i>Previously, annxingyuan (Ann Yuan) wrote…</i></summary><blockquote>

Done

I moved the test to the webgl backend only.
</blockquote></details>

cool, I did not see the webgl backend only test?


<!-- Sent from Reviewable.io -->

2020-10-12 20:09 UTC, annxingyuan reviewed
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4033)* status: 0 of 1 approvals obtained (waiting on @annxingyuan, @pyu10055, and @tafsiri)

___
*[tfjs-core/src/ops/mean_test.ts, line 22 at r4](https://reviewable.io/reviews/tensorflow/tfjs/4033#-MJSbrqx2MuWumXzYFt_:-MJTQZlf4HmF4ZwJeCPl:bcrfpas) ([raw file](https://github.com/tensorflow/tfjs/blob/4eb81c74fc656fb7f7724f534cb08fc2c0e954c1/tfjs-core/src/ops/mean_test.ts#L22)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

cool, I did not see the webgl backend only test?
</blockquote></details>

https://github.com/tensorflow/tfjs/pull/4033/files#diff-c6e4bfd0982ba56ef4fab7f9a7f10183


<!-- Sent from Reviewable.io -->

2020-10-14 12:23 UTC, merged