Implement HashTable ops
tensorflow/tfjs pull request #4060
Opened 2020-10-13 01:26 UTC by lina128

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

2020-10-13 17:07 UTC, pyu10055 requested changes
Beautiful, thank you! just a couple minor comments. 

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4060#-:-MJXtqiABCeW_a_CpEWV:b-eldvtm)* status: 0 of 1 approvals obtained (waiting on @lina128 and @pyu10055)

___
*[e2e/integration_tests/convert_predict.py, line 390 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4060#-MJXkKAl8uKNqso5LkoL:-MJXkKAl8uKNqso5LkoM:b-88xy4a) ([raw file](https://github.com/tensorflow/tfjs/blob/27e277b73ada7bd47bc82af7eb4fa7f056365b30/e2e/integration_tests/convert_predict.py#L390)):*
> ```Python
>       keys_tensor = tf.constant([1, 2])
>       vals_tensor = tf.constant([3, 4])
>       input_tensor = tf.constant([1, 5])
> ```

this variable is not used?
___
*[tfjs-converter/python/tensorflowjs/op_list/hash_table.json, line 33 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4060#-MJXr-lo3-h3gEVuYsB0:-MJXr-lo3-h3gEVuYsB1:b-2c2vsq) ([raw file](https://github.com/tensorflow/tfjs/blob/27e277b73ada7bd47bc82af7eb4fa7f056365b30/tfjs-converter/python/tensorflowjs/op_list/hash_table.json#L33)):*
> ```JSON
>     "category": "hash_table",
>     "inputs": [],
>     "attrs": [
> ```

we are using the container attribute?
___
*[tfjs-converter/src/executor/hash_table.ts, line 67 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4060#-MJXvQ065hlnTCb5Gj9W:-MJXvQ065hlnTCb5Gj9X:b-6nsgwk) ([raw file](https://github.com/tensorflow/tfjs/blob/27e277b73ada7bd47bc82af7eb4fa7f056365b30/tfjs-converter/src/executor/hash_table.ts#L67)):*
> ```XML
>    * @param values Values to store in the hashtable.
>    */
>   async import(keys: Tensor, values: Tensor): Promise<Tensor> {
> ```

curious if the keys dtype is string, what is return values from keys.data()?
Is it uint8Array? or string?
___
*[tfjs-converter/src/executor/resource_manager.ts, line 3 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4060#-MJXuqDDAvb3K40s9RIZ:-MJXuqDDAvb3K40s9RI_:bb6ht35) ([raw file](https://github.com/tensorflow/tfjs/blob/27e277b73ada7bd47bc82af7eb4fa7f056365b30/tfjs-converter/src/executor/resource_manager.ts#L3)):*
> ```XML
> /**
>  * @license
>  * Copyright 2018 Google LLC. All Rights Reserved.
> ```

2020
___
*[tfjs-converter/src/executor/resource_manager.ts, line 28 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4060#-MJXufy3DZGTx0XKuRgQ:-MJXufy3DZGTx0XKuRgR:b-ikp3oe) ([raw file](https://github.com/tensorflow/tfjs/blob/27e277b73ada7bd47bc82af7eb4fa7f056365b30/tfjs-converter/src/executor/resource_manager.ts#L28)):*
> ```XML
>       readonly hashTableMap: HashTableMap = {}) {}
> 
>   addHashTable(name: string, hashTable: HashTable) {
> ```

please add jsdoc for the public methods
___
*[tfjs-converter/src/operations/executors/hash_table_executor_test.ts, line 3 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4060#-MJXuz_P4jiyHjnMI199:-MJXuz_P4jiyHjnMI19A:bb6ht35) ([raw file](https://github.com/tensorflow/tfjs/blob/27e277b73ada7bd47bc82af7eb4fa7f056365b30/tfjs-converter/src/operations/executors/hash_table_executor_test.ts#L3)):*
> ```XML
> /**
>  * @license
>  * Copyright 2018 Google LLC. All Rights Reserved.
> ```

2020
___
*[tfjs-core/src/io/io_utils.ts, line 217 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4060#-MJXszKK1wRuaFWxTpen:-MJXszKK1wRuaFWxTpeo:b-53ddzh) ([raw file](https://github.com/tensorflow/tfjs/blob/27e277b73ada7bd47bc82af7eb4fa7f056365b30/tfjs-core/src/io/io_utils.ts#L217)):*
> ```XML
>         const imageTensor = tensor(image, shape, 'float32');
>         out[name] = complex(realTensor, imageTensor);
>         realTensor.dispose();
> ```

is this change related?


<!-- Sent from Reviewable.io -->

2020-10-13 17:08 UTC, pyu10055 reviewed
> Reviewed 30 of 30 files at r1.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4060)* status: 0 of 1 approvals obtained (waiting on @lina128 and @pyu10055)



<!-- Sent from Reviewable.io -->

2020-10-13 18:27 UTC, lina128 reviewed
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4060)* status: 0 of 1 approvals obtained (waiting on @pyu10055)

___
*[e2e/integration_tests/convert_predict.py, line 390 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4060#-MJXkKAl8uKNqso5LkoL:-MJY9upL2vTvJFeTnkLM:bss4a2b) ([raw file](https://github.com/tensorflow/tfjs/blob/27e277b73ada7bd47bc82af7eb4fa7f056365b30/e2e/integration_tests/convert_predict.py#L390)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

this variable is not used?
</blockquote></details>

Removed.
___
*[tfjs-converter/python/tensorflowjs/op_list/hash_table.json, line 33 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4060#-MJXr-lo3-h3gEVuYsB0:-MJY9yaB1MNsTDsxVQ9R:bfpfr1w) ([raw file](https://github.com/tensorflow/tfjs/blob/27e277b73ada7bd47bc82af7eb4fa7f056365b30/tfjs-converter/python/tensorflowjs/op_list/hash_table.json#L33)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

we are using the container attribute?
</blockquote></details>

We are not using container attribute. In this case, should we still map it or skip it?
___
*[tfjs-converter/src/executor/hash_table.ts, line 67 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4060#-MJXvQ065hlnTCb5Gj9W:-MJYAciI3wDXKfPbAq3r:bv89ioc) ([raw file](https://github.com/tensorflow/tfjs/blob/27e277b73ada7bd47bc82af7eb4fa7f056365b30/tfjs-converter/src/executor/hash_table.ts#L67)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

curious if the keys dtype is string, what is return values from keys.data()?
Is it uint8Array? or string?
</blockquote></details>

It returns string: https://github.com/tensorflow/tfjs/blob/master/tfjs-core/src/tensor.ts#L336
I can change the e2e test to use string as key to verify it.
___
*[tfjs-converter/src/executor/resource_manager.ts, line 3 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4060#-MJXuqDDAvb3K40s9RIZ:-MJYAoOP0aheXi5-BJEE:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/27e277b73ada7bd47bc82af7eb4fa7f056365b30/tfjs-converter/src/executor/resource_manager.ts#L3)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

2020
</blockquote></details>

Done.
___
*[tfjs-converter/src/executor/resource_manager.ts, line 28 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4060#-MJXufy3DZGTx0XKuRgQ:-MJYCezx-DhuHPWtloEi:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/27e277b73ada7bd47bc82af7eb4fa7f056365b30/tfjs-converter/src/executor/resource_manager.ts#L28)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

please add jsdoc for the public methods
</blockquote></details>

Done.
___
*[tfjs-converter/src/operations/executors/hash_table_executor_test.ts, line 3 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4060#-MJXuz_P4jiyHjnMI199:-MJYCiUtCT4AATU_EjER:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/27e277b73ada7bd47bc82af7eb4fa7f056365b30/tfjs-converter/src/operations/executors/hash_table_executor_test.ts#L3)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

2020
</blockquote></details>

Done.
___
*[tfjs-core/src/io/io_utils.ts, line 217 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4060#-MJXszKK1wRuaFWxTpen:-MJYCjJy5bz_R8srxoML:bijyi3p) ([raw file](https://github.com/tensorflow/tfjs/blob/27e277b73ada7bd47bc82af7eb4fa7f056365b30/tfjs-core/src/io/io_utils.ts#L217)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

is this change related?
</blockquote></details>

This is not related, but fixes a memory leak bug. See PR description #4 and #5.


<!-- Sent from Reviewable.io -->

2020-10-13 22:06 UTC, lina128 reviewed
Thank you for the review, Ping! I addressed the comments, please take another look.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4060#-:-MJYzxmaENcxukhw6p_f:bbkfjth)* status: 0 of 1 approvals obtained (waiting on @pyu10055)



<!-- Sent from Reviewable.io -->

2020-10-14 03:08 UTC, pyu10055 approved these changes
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4060)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @lina128 and @pyu10055)

___
*[tfjs-converter/python/tensorflowjs/op_list/hash_table.json, line 33 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4060#-MJXr-lo3-h3gEVuYsB0:-MJ_3PwP1MAnXKZo3EyN:b-lxsjso) ([raw file](https://github.com/tensorflow/tfjs/blob/27e277b73ada7bd47bc82af7eb4fa7f056365b30/tfjs-converter/python/tensorflowjs/op_list/hash_table.json#L33)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

We are not using container attribute. In this case, should we still map it or skip it?
</blockquote></details>

Maybe just add for the sake of completeness, since some of the attribute we don't use are listed anyway.
___
*[tfjs-converter/src/executor/resource_manager.ts, line 60 at r2](https://reviewable.io/reviews/tensorflow/tfjs/4060#-MJ_3yGE2_-3mi1yFAfP:-MJ_3yGE2_-3mi1yFAfQ:b-q94965) ([raw file](https://github.com/tensorflow/tfjs/blob/e51d87f6b53bf038d6d80f98e1f40318d997f21b/tfjs-converter/src/executor/resource_manager.ts#L60)):*
> ```XML
> 
>   /**
>    * Dispose `ResourceManager`, including its hashTables and tensors in them/
> ```

replace / at the end with .


<!-- Sent from Reviewable.io -->

2020-10-14 03:25 UTC, lina128 reviewed
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4060)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @pyu10055)

___
*[tfjs-converter/python/tensorflowjs/op_list/hash_table.json, line 33 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4060#-MJXr-lo3-h3gEVuYsB0:-MJ_7okm2gLJBFOIR4dx:bb6sh2i) ([raw file](https://github.com/tensorflow/tfjs/blob/27e277b73ada7bd47bc82af7eb4fa7f056365b30/tfjs-converter/python/tensorflowjs/op_list/hash_table.json#L33)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

Maybe just add for the sake of completeness, since some of the attribute we don't use are listed anyway.
</blockquote></details>

Ack.
___
*[tfjs-converter/src/executor/resource_manager.ts, line 60 at r2](https://reviewable.io/reviews/tensorflow/tfjs/4060#-MJ_3yGE2_-3mi1yFAfP:-MJ_7u5b8w5urWr_DGcF:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/e51d87f6b53bf038d6d80f98e1f40318d997f21b/tfjs-converter/src/executor/resource_manager.ts#L60)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

replace / at the end with .
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-14 03:53 UTC, merged