Add shuffleCombo
tensorflow/tfjs pull request #4446
Opened 2020-12-27 21:22 UTC by GantMan

When shuffling an array of X and Y it's important that X still corresponds with Y.

This is a useful utility for shuffling training data that is in JavaScript form.

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

2020-12-30 16:28 UTC, GantMan commented
@pyu10055  -  I used this to shuffle X and Y in the same way.

2020-12-31 22:11 UTC, GantMan commented
I'm having trouble seeing what is failing

2021-01-05 16:00 UTC, tafsiri commented
@GantMan can you access https://pantheon.corp.google.com/cloud-build/builds/2030dc6f-f8da-4ac2-ad6c-c0ce5ce62c14?project=learnjs-174218

![A6hC2xuQGM2PvW6](https://user-images.githubusercontent.com/26408/103668544-35453d80-4f45-11eb-85f5-945087fa194d.png)

2021-01-05 16:11 UTC, GantMan commented
No I cannot access pantheon bc I do not have a google.com email.

Also, the `Details` link lands me in Google Cloud Build, which shows this:
![image](https://user-images.githubusercontent.com/997157/103669799-6c642080-4f3e-11eb-97c3-b7e6b234acc7.png)

2021-01-05 16:18 UTC, tafsiri commented
Wrt to the details link, it should give you access if you join one of the two mailing lists linked above (I can't remember if a google account is required but it might be). Are you already on one of those lists?

2021-01-05 16:37 UTC, GantMan commented
@tafsiri - you rock.   I missed that note, and now I can see the build issue.  I'll dig into it.

2021-01-05 19:20 UTC, GantMan commented
Thanks @tafsiri for getting me access to the logs.   Sorry to bounce this back and forth so many times but I couldn't run the scripts on Windows, so I needed that access.

Should be good for eval now.

2021-01-06 17:34 UTC, pyu10055 requested changes
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4446)* status: 0 of 1 approvals obtained (waiting on @GantMan and @pyu10055)

___
*[tfjs-core/src/util_base.ts, line 72 at r4](https://reviewable.io/reviews/tensorflow/tfjs/4446#-MQNkMRQ64Y0OkRg9_ge:-MQNkMRQ64Y0OkRg9_gf:b-po4e81) ([raw file](https://github.com/tensorflow/tfjs/blob/5535884fb9bbef95b280ba504103393e0e7a4ee7/tfjs-core/src/util_base.ts#L72)):*
> ```XML
> // tslint:disable-next-line:no-any
>                       array2: any[]|Uint32Array|Int32Array|Float32Array): void {
>   console.assert(array.length === array2.length);
> ```

can you throw exception instead of using console.assert? TFJS support other platforms where console.assert might not be supported.


<!-- Sent from Reviewable.io -->

2021-01-07 16:08 UTC, GantMan commented
@pyu10055 - good call, all fixed.

2021-01-07 16:09 UTC, GantMan reviewed
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4446)* status: 0 of 1 approvals obtained (waiting on @GantMan)



<!-- Sent from Reviewable.io -->

2021-01-07 16:10 UTC, GantMan reviewed
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4446)* status: 0 of 1 approvals obtained (waiting on @pyu10055)

___
*[tfjs-core/src/util_base.ts, line 72 at r4](https://reviewable.io/reviews/tensorflow/tfjs/4446#-MQNkMRQ64Y0OkRg9_ge:-MQSbB8M4vU1u6-49BAD:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/5535884fb9bbef95b280ba504103393e0e7a4ee7/tfjs-core/src/util_base.ts#L72)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

can you throw exception instead of using console.assert? TFJS support other platforms where console.assert might not be supported.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-13 15:43 UTC, GantMan commented
@pyu10055 - anything else on this one?

2021-01-14 16:35 UTC, pyu10055 reviewed
Thanks Gant, can you add a unit test for this change? 

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4446#-:-MR0jx5Z8yY8dASY6937:b-ncos23)* status: 0 of 1 approvals obtained (waiting on @pyu10055)



<!-- Sent from Reviewable.io -->

2021-01-15 18:06 UTC, GantMan reviewed
@pyu10055 - I noticed there was no test for `util.shuffle` either so I added a test for the existing `shuffle` and for my new `shuffleCombo`.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4446#-:-MR6DOYK6ojDJ1qcwOfB:bz5ug1q)* status: 0 of 1 approvals obtained (waiting on @pyu10055)



<!-- Sent from Reviewable.io -->

2021-01-15 18:06 UTC, GantMan reviewed
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4446#-:-MR6DS603dg561jj5msX:b-jbsf8z)* status: 0 of 1 approvals obtained (waiting on @pyu10055)



<!-- Sent from Reviewable.io -->

2021-01-15 18:06 UTC, GantMan reviewed
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4446)* status: 0 of 1 approvals obtained (waiting on @pyu10055)



<!-- Sent from Reviewable.io -->

2021-01-15 20:45 UTC, pyu10055 approved these changes
thanks

2021-01-15 20:47 UTC, merged