Re-enable Android nightly tests
tensorflow/tfjs pull request #4664
Opened 2021-02-09 20:32 UTC by mattsoulanille

Also make `run_flaky` tests (the tests for testing the `run_flaky.js` test runner script) deterministic. Flaky test running is currently only enabled for e2e tests. We'll see if there's an improvement in e2e test reliability vs other tests and then perhaps expand flaky testing to all BrowserStack tests.

Closes #4353.

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

2021-02-09 20:36 UTC, mattsoulanille commented
[Here is a `_NIGHTLY=true` run for webgl.](https://console.cloud.google.com/cloud-build/builds/c29e9b0b-f64b-4869-a29a-66c8f6168620?project=834911136599)

2021-02-10 22:43 UTC, pyu10055 requested changes
Thanks

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4664#-:-MTD6LTo7yHzU1MBPPiP:b-zcjvte)* status: 0 of 1 approvals obtained (waiting on @mattsoulanille)

___
*[scripts/run_flaky_test_helper.js, line 18 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4664#-MTD6H0LD5lqYXMUELvJ:-MTD6H0LD5lqYXMUELvK:b-m8z055) ([raw file](https://github.com/tensorflow/tfjs/blob/c7fe89c7156313e7ce3e46673dd4b235e0a4b9c9/scripts/run_flaky_test_helper.js#L18)):*
> ```JavaScript
> const fs = require('fs');
> 
> if (!fs.existsSync('./flaky_test_has_run')) {
> ```

use a const for the filename


<!-- Sent from Reviewable.io -->

2021-02-11 15:12 UTC, mattsoulanille reviewed
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4664)* status: 0 of 1 approvals obtained (waiting on @pyu10055)

___
*[scripts/run_flaky_test_helper.js, line 18 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4664#-MTD6H0LD5lqYXMUELvJ:-MTGdhuQ7qlQZzGRLvg8:b-qu6n94) ([raw file](https://github.com/tensorflow/tfjs/blob/c7fe89c7156313e7ce3e46673dd4b235e0a4b9c9/scripts/run_flaky_test_helper.js#L18)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

use a const for the filename
</blockquote></details>

Good point. Done.


<!-- Sent from Reviewable.io -->

2021-02-11 16:20 UTC, pyu10055 approved these changes
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4664)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @pyu10055)



<!-- Sent from Reviewable.io -->

2021-02-11 16:21 UTC, merged