Add --help menu to BrowserStack benchmark
tensorflow/tfjs pull request #5196
Opened 2021-06-08 23:07 UTC by ClaireXP

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs/5196)

2021-06-09 16:40 UTC, mattsoulanille requested changes
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5196)* status: 0 of 1 approvals obtained (waiting on @ClaireXP and @lina128)

___
*[e2e/benchmarks/browserstack-benchmark/app.js, line 158 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5196#-MblbeNbD5Zw1S4H2fjR:-MblbeNc8dktcGXyHqnh:b-1tbp46) ([raw file](https://github.com/tensorflow/tfjs/blob/4ae488807dfcb94f48c35d50a3ea5604e6ad03e9/e2e/benchmarks/browserstack-benchmark/app.js#L158)):*
> ```
>     description: 'The following commands are available:'
> ```
It's better to have the description of the program, `app.js`, here. ArgParse should automatically print something to say what arguments are available (or make it clear through formatting).


<!-- Sent from Reviewable.io -->

2021-06-09 20:01 UTC, mattsoulanille approved these changes
LGTM! Will merge after @lina128 takes a look.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5196#-:-MbmM1EH6ylHZtoFyk3u:b-n2uegr)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @lina128)

___
*[e2e/benchmarks/browserstack-benchmark/app.js, line 158 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5196#-MblbeNbD5Zw1S4H2fjR:-MbmLhHa4qDiNnLfdqOX:b-lhs4gy) ([raw file](https://github.com/tensorflow/tfjs/blob/4ae488807dfcb94f48c35d50a3ea5604e6ad03e9/e2e/benchmarks/browserstack-benchmark/app.js#L158)):*
<details><summary><i>Previously, mattsoulanille (Matthew Soulanille) wrote…</i></summary><blockquote>

> ```
>     description: 'The following commands are available:'
> ```
It's better to have the description of the program, `app.js`, here. ArgParse should automatically print something to say what arguments are available (or make it clear through formatting).
</blockquote></details>

The new description looks good. Thanks for changing it!


<!-- Sent from Reviewable.io -->

2021-06-10 16:08 UTC, lina128 requested changes
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5196)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @ClaireXP)

___
*[e2e/benchmarks/browserstack-benchmark/app.js, line 23 at r2](https://reviewable.io/reviews/tensorflow/tfjs/5196#-MbqfT7M03dRdN73tzsn:-MbqfT7M03dRdN73tzso:ba0996b) ([raw file](https://github.com/tensorflow/tfjs/blob/b158bd308c952a55f29b58f881d3854f12bea7f6/e2e/benchmarks/browserstack-benchmark/app.js#L23)):*
> ```
> ArgumentParse
> ```
camelCase


<!-- Sent from Reviewable.io -->

2021-06-10 16:51 UTC, lina128 approved these changes

2021-06-11 14:40 UTC, merged