Switch WebGL TopK algorithm to use bitonic
tensorflow/tfjs pull request #5233
Opened 2021-06-17 23:47 UTC by ahmedsabie

Algorithm based on this [paper] (https://anilshanbhag.in/static/papers/gputopk_sigmod18.pdf)

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

2021-06-18 18:07 UTC, lina128 reviewed
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5233)* status: 0 of 1 approvals obtained (waiting on @ahmedsabie and @pyu10055)

___
*[tfjs-backend-webgl/src/kernels/TopK.ts, line 68 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5233#-McVF4W9-KmaZiaxhx9-:-McVF4W9-KmaZiaxhx90:b-l84w3y) ([raw file](https://github.com/tensorflow/tfjs/blob/a3cec8849c439ccf9cea6bde7ccc4dce93c57210/tfjs-backend-webgl/src/kernels/TopK.ts#L68)):*
> ```
> indices
> ```
Can we call this intermediateResult or sortedList? `indices` indicates the values of this list is indices, which is not in this case.
___
*[tfjs-backend-webgl/src/kernels/TopK.ts, line 70 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5233#-McVIJNp95KRlOnGVro5:-McVIJNq72i6D-4UEtK9:b-7yne85) ([raw file](https://github.com/tensorflow/tfjs/blob/a3cec8849c439ccf9cea6bde7ccc4dce93c57210/tfjs-backend-webgl/src/kernels/TopK.ts#L70)):*
> ```
> () => indices === null ? [x] : [x, indices]
> ```
Why do we need to pass intermediateResult(indices) as additional input? Can it substitute x in each loop?


<!-- Sent from Reviewable.io -->

2021-06-18 18:32 UTC, ahmedsabie reviewed
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5233)* status: 0 of 1 approvals obtained (waiting on @lina128 and @pyu10055)

___
*[tfjs-backend-webgl/src/kernels/TopK.ts, line 68 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5233#-McVF4W9-KmaZiaxhx9-:-McVNUs20VUAsw_NBOiS:b-blmhxk) ([raw file](https://github.com/tensorflow/tfjs/blob/a3cec8849c439ccf9cea6bde7ccc4dce93c57210/tfjs-backend-webgl/src/kernels/TopK.ts#L68)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
> indices
> ```
Can we call this intermediateResult or sortedList? `indices` indicates the values of this list is indices, which is not in this case.
</blockquote></details>

But it is holding indices, value are extracted later
___
*[tfjs-backend-webgl/src/kernels/TopK.ts, line 70 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5233#-McVIJNp95KRlOnGVro5:-McVNbOB78OfnLbcfUc3:brmqcgv) ([raw file](https://github.com/tensorflow/tfjs/blob/a3cec8849c439ccf9cea6bde7ccc4dce93c57210/tfjs-backend-webgl/src/kernels/TopK.ts#L70)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
> () => indices === null ? [x] : [x, indices]
> ```
Why do we need to pass intermediateResult(indices) as additional input? Can it substitute x in each loop?
</blockquote></details>

I made the GPU kernel only have one output which is indices which cuts the outputs size in half, otherwise you have to output both values and indices at each step if you want to replace x


<!-- Sent from Reviewable.io -->

2021-06-18 18:33 UTC, pyu10055 requested changes
Great work, Thanks!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5233#-:-McVOZeEAn3InnygU3qw:b-g00ylh)* status: 0 of 1 approvals obtained (waiting on @ahmedsabie and @lina128)

___
*[tfjs-backend-cpu/src/shared.ts, line 56 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5233#-McVGrVe1g_ymD4knEmf:-McVGrVe1g_ymD4knEmg:b-miqcbq) ([raw file](https://github.com/tensorflow/tfjs/blob/8b28347c8450f2bb04f7a13e445f193a6a2b1581/tfjs-backend-cpu/src/shared.ts#L56)):*
> ```XML
> export {subImpl} from './kernels/Sub';
> export {tileImpl} from './kernels/Tile_impl';
> export {topKImpl} from './kernels/TopK_impl';
> ```

you can leave the impl export here, since it can be used for cpu forwarding for small input size.
___
*[tfjs-backend-webgl/src/top_k_gpu.ts, line 32 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5233#-McVN6PbB8g7hKhT4wRu:-McVN6PbB8g7hKhT4wRv:b-kz6efe) ([raw file](https://github.com/tensorflow/tfjs/blob/a3cec8849c439ccf9cea6bde7ccc4dce93c57210/tfjs-backend-webgl/src/top_k_gpu.ts#L32)):*
> ```XML
>   inc: WebGLUniformLocation;
> 
>   constructor(n: number, shape: number[], firstPass: boolean) {
> ```

can you add jdoc for explaining the prameters, thanks
___
*[tfjs-backend-webgl/src/top_k_gpu.ts, line 85 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5233#-McVNo2z70AwLVSNez2P:-McVNo2z70AwLVSNez2Q:bxmqjfg) ([raw file](https://github.com/tensorflow/tfjs/blob/a3cec8849c439ccf9cea6bde7ccc4dce93c57210/tfjs-backend-webgl/src/top_k_gpu.ts#L85)):*
> ```XML
>         this.inc = gpgpu.getUniformLocation(webGLProgram, 'inc');
>       }
>       gpgpu.gl.uniform1f(this.negativeInf, -Infinity);
> ```

`Number.NEGTIVE_INFINITY`?
___
*[tfjs-backend-webgl/src/top_k_gpu.ts, line 97 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5233#-McVO-Aj0wA3AoPwAVBu:-McVO-Aj0wA3AoPwAVBv:b-kz6efe) ([raw file](https://github.com/tensorflow/tfjs/blob/a3cec8849c439ccf9cea6bde7ccc4dce93c57210/tfjs-backend-webgl/src/top_k_gpu.ts#L97)):*
> ```XML
>   userCode: string;
> 
>   constructor(n: number, k: number, shape: number[], firstPass: boolean) {
> ```

can you add jdoc for explaining the prameters, thanks
___
*[tfjs-backend-webgl/src/kernel_utils/shared.ts, line 68 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5233#-McVHgvh0YSgb7lNyLaW:-McVHgvh0YSgb7lNyLaX:b-si23yw) ([raw file](https://github.com/tensorflow/tfjs/blob/8b28347c8450f2bb04f7a13e445f193a6a2b1581/tfjs-backend-webgl/src/kernel_utils/shared.ts#L68)):*
> ```XML
>   subImpl: subImplCPU,
>   tileImpl: tileImplCPU,
>   topKImpl: topKImplCPU,
> ```

same as above, cpu impl can still be fast for small input size.
___
*[tfjs-backend-webgl/src/kernels/TopK.ts, line 63 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5233#-McVJqf12TMujEtLBFG0:-McVJqf12TMujEtLBFG1:b-bxc99d) ([raw file](https://github.com/tensorflow/tfjs/blob/a3cec8849c439ccf9cea6bde7ccc4dce93c57210/tfjs-backend-webgl/src/kernels/TopK.ts#L63)):*
> ```XML
>   const xSize = util.sizeFromShape(xShape);
>   const batch = xSize / lastDim;
>   x.shape = [batch, lastDim];
> ```

should you call reshape op instead of change the shape value directly to reshape the input `x`?
___
*[tfjs-backend-webgl/src/kernels/TopK.ts, line 70 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5233#-McVIJNp95KRlOnGVro5:-McVKFsU-_MQ8VYKcdn3:b6x09d2) ([raw file](https://github.com/tensorflow/tfjs/blob/a3cec8849c439ccf9cea6bde7ccc4dce93c57210/tfjs-backend-webgl/src/kernels/TopK.ts#L70)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
> () => indices === null ? [x] : [x, indices]
> ```
Why do we need to pass intermediateResult(indices) as additional input? Can it substitute x in each loop?
</blockquote></details>

I think he is reusing the input `x`, but with updated indices for access the values.
___
*[tfjs-backend-webgl/src/kernels/TopK.ts, line 124 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5233#-McVL8XNAwPuazUhqIFg:-McVL8XNAwPuazUhqIFh:b-43tk8h) ([raw file](https://github.com/tensorflow/tfjs/blob/a3cec8849c439ccf9cea6bde7ccc4dce93c57210/tfjs-backend-webgl/src/kernels/TopK.ts#L124)):*
> ```XML
>   // dimension is k.
>   xShape[xShape.length - 1] = k;
>   indices.shape = xShape;
> ```

you should use reshape to update the values and indices shapes.


<!-- Sent from Reviewable.io -->

2021-06-18 20:09 UTC, lina128 reviewed
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5233)* status: 0 of 1 approvals obtained (waiting on @ahmedsabie and @lina128)

___
*[tfjs-backend-webgl/src/kernels/TopK.ts, line 68 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5233#-McVF4W9-KmaZiaxhx9-:-McVizcqBfYEzTWGGWYJ:btook0o) ([raw file](https://github.com/tensorflow/tfjs/blob/a3cec8849c439ccf9cea6bde7ccc4dce93c57210/tfjs-backend-webgl/src/kernels/TopK.ts#L68)):*
<details><summary><i>Previously, ahmedsabie wrote…</i></summary><blockquote>

But it is holding indices, value are extracted later
</blockquote></details>

Ah, right, I missed that, it sets i. Can you summarize the algorithm in the shader program, because the implementation is different than Algorithm2. Thanks.


<!-- Sent from Reviewable.io -->

2021-06-18 20:47 UTC, lina128 reviewed
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5233)* status: 0 of 1 approvals obtained (waiting on @ahmedsabie and @lina128)

___
*[tfjs-backend-webgl/src/top_k_gpu.ts, line 32 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5233#-McVs144D_LwobA-9xag:-McVs144D_LwobA-9xah:b-q8q3q5) ([raw file](https://github.com/tensorflow/tfjs/blob/a3cec8849c439ccf9cea6bde7ccc4dce93c57210/tfjs-backend-webgl/src/top_k_gpu.ts#L32)):*
> ```
> n
> ```
Can this be a uniform? Otherwise, for different n, there will be different shader created.


<!-- Sent from Reviewable.io -->

2021-06-19 01:23 UTC, lina128 reviewed
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5233)* status: 0 of 1 approvals obtained (waiting on @ahmedsabie and @pyu10055)

___
*[tfjs-backend-webgl/src/top_k_gpu.ts, line 49 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5233#-McWLkA9005Wn-B_nj3l:-McWLkA9005Wn-B_nj3m:b24of60) ([raw file](https://github.com/tensorflow/tfjs/blob/a3cec8849c439ccf9cea6bde7ccc4dce93c57210/tfjs-backend-webgl/src/top_k_gpu.ts#L49)):*
> ```
> // Maps both indices in a pair to the first index
> ```
As discussed offline, sugg annotation:
// We compare elements pair-wise within a group of size 2*inc. The comparing rule for each group alternates between ascending and descending. Within each group, we compare each pair at position i and i+inc. To decide whether an element at position i is x0 or x1, we mod it by 2*inc, if the result is smaller than inc, it is in the first half of the group, we denote it as x0, otherwise we denote it as x1. For example, as shown in the paper Figure5(a), element[1] is in the second half of the group when group size is 2, but it is in the first half of the group when group size is 4.
___
*[tfjs-backend-webgl/src/top_k_gpu.ts, line 66 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5233#-McWTnD_D-CNEdnUsD4f:-McWTnD_D-CNEdnUsD4g:bfbpv9k) ([raw file](https://github.com/tensorflow/tfjs/blob/a3cec8849c439ccf9cea6bde7ccc4dce93c57210/tfjs-backend-webgl/src/top_k_gpu.ts#L66)):*
> ```
> float(i0)
> ```
The output dtype is 'int32', do we need to convert to float here?
___
*[tfjs-backend-webgl/src/kernels/TopK.ts, line 63 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5233#-McVJqf12TMujEtLBFG0:-McWW1gK8CkllJ6-vPiD:b32v57) ([raw file](https://github.com/tensorflow/tfjs/blob/a3cec8849c439ccf9cea6bde7ccc4dce93c57210/tfjs-backend-webgl/src/kernels/TopK.ts#L63)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

should you call reshape op instead of change the shape value directly to reshape the input `x`?
</blockquote></details>

+1
___
*[tfjs-backend-webgl/src/kernels/TopK.ts, line 73 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5233#-McWYbzPAqwCSEvraclq:-McWYbzPAqwCSEvraclr:bkcfcwj) ([raw file](https://github.com/tensorflow/tfjs/blob/a3cec8849c439ccf9cea6bde7ccc4dce93c57210/tfjs-backend-webgl/src/kernels/TopK.ts#L73)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
>   const disposeIntermediateTensorInfoOrNull = (tensorInfo: TensorInfo) => {
>     if (tensorInfo !== null) {
>       backend.disposeIntermediateTensorInfo(tensorInfo);
>     }
>   };
> ```
</details>

Can you move this function outside of the current function?
___
*[tfjs-backend-webgl/src/kernels/TopK.ts, line 80 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5233#-McWYGDB3WUNNaLYyn8c:-McWYGDB3WUNNaLYyn8d:b-vsdd6c) ([raw file](https://github.com/tensorflow/tfjs/blob/a3cec8849c439ccf9cea6bde7ccc4dce93c57210/tfjs-backend-webgl/src/kernels/TopK.ts#L80)):*
> ```
> inputs.length === 1
> ```
sugg code style: `inputs.length === 1 /* firstPass */`
___
*[tfjs-backend-webgl/src/kernels/TopK.ts, line 96 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5233#-McWiU2104BWult_tQKJ:-McWiU2104BWult_tQKK:b-5ue9x7) ([raw file](https://github.com/tensorflow/tfjs/blob/a3cec8849c439ccf9cea6bde7ccc4dce93c57210/tfjs-backend-webgl/src/kernels/TopK.ts#L96)):*
> ```
>  // Step 2: merge
> ```
Move this annotation to above the for loop.
___
*[tfjs-backend-webgl/src/kernels/TopK.ts, line 107 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5233#-McWb0Rk6B2E6rIQbDUe:-McWb0Rk6B2E6rIQbDUf:b733lfb) ([raw file](https://github.com/tensorflow/tfjs/blob/a3cec8849c439ccf9cea6bde7ccc4dce93c57210/tfjs-backend-webgl/src/kernels/TopK.ts#L107)):*
> ```
> // Step 3: rebuild
> ```
Move this annotation to above `const len = kPow2 / 2;`


<!-- Sent from Reviewable.io -->

2021-06-19 02:11 UTC, lina128 approved these changes
Absolutely excellent work, Ahmed! You can benchmark the kernel following this example: https://github.com/tensorflow/tfjs/pull/3168

Please update before and after perf. Thanks!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5233#-:-McX161T-y5h3_Zqsxxk:btalwj)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @ahmedsabie and @pyu10055)

___
*[tfjs-backend-webgl/src/kernels/TopK.ts, line 119 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5233#-McX-spX6z-2E2zuKE2O:-McX-spX6z-2E2zuKE2P:b-3utgjn) ([raw file](https://github.com/tensorflow/tfjs/blob/a3cec8849c439ccf9cea6bde7ccc4dce93c57210/tfjs-backend-webgl/src/kernels/TopK.ts#L119)):*
> ```
> x
> ```
This x should be the reshaped x, right?


<!-- Sent from Reviewable.io -->

2021-06-19 16:00 UTC, pyu10055 requested changes
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5233)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @ahmedsabie and @pyu10055)

___
*[tfjs-backend-webgl/src/top_k_gpu.ts, line 111 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5233#-McZudyH6uiKxz2Ttol8:-McZudyJ6WsGrQ-1H0Kt:b-lzm9h9) ([raw file](https://github.com/tensorflow/tfjs/blob/a3cec8849c439ccf9cea6bde7ccc4dce93c57210/tfjs-backend-webgl/src/top_k_gpu.ts#L111)):*
> ```XML
>          int elemIdx = coords[1];
> 
>          int i = elemIdx < ${k} ? elemIdx : (elemIdx * 2 - imod(elemIdx, ${k}));
> ```

can you explain the meaning of `(elemIdx * 2 - imod(elemIdx, ${k})`?
___
*[tfjs-backend-webgl/src/kernels/TopK.ts, line 99 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5233#-Mc_-1DSCcdj5pU8lsxr:-Mc_-1DSCcdj5pU8lsxs:b-833jjd) ([raw file](https://github.com/tensorflow/tfjs/blob/a3cec8849c439ccf9cea6bde7ccc4dce93c57210/tfjs-backend-webgl/src/kernels/TopK.ts#L99)):*
> ```
> inputs.length === 1
> ```
Will this every be true for merge program, since the SwapProgram has been executed and indices will be not null anymore?


<!-- Sent from Reviewable.io -->

2021-06-19 16:29 UTC, lina128 reviewed
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5233)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @ahmedsabie and @pyu10055)

___
*[tfjs-backend-webgl/src/top_k_gpu.ts, line 111 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5233#-McZudyH6uiKxz2Ttol8:-Mc_0UtWBQ5_1ESiWRTd:b-9b99q7) ([raw file](https://github.com/tensorflow/tfjs/blob/a3cec8849c439ccf9cea6bde7ccc4dce93c57210/tfjs-backend-webgl/src/top_k_gpu.ts#L111)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

can you explain the meaning of `(elemIdx * 2 - imod(elemIdx, ${k})`?
</blockquote></details>

This is how I understand it, let me know whether it's readable, we definitely need to add some annotations here:
The output size is half of the previous size. If the previous sequence is | | | |_ _ _ _ | | | | _ _ _ _  (k=4), we only need to output the indices at positions |, the indices at positions _ can be thrown away, see Figure5(b) After Phase2 (Merge phase) for example, we only need to output the orange bars. The output sequence should look like this 
| | | | | | | |. Because the sequence is halved, to map the output index back to the previous sequence to find the corresponding value, we need to *2. When we double the index, we basically interpolate a position, so 2i looks like | _ | _ | _ | _ | _ | _ | _. We move the | to the first k position of each 2k positions by `- elemIdx % k`. E.g. for output at index 4,5,6,7, we want to get the corresponding element at original index 8,9,10,11, for output at index 8,9,10,11, we want to get the corresponding element at original index 16,17,18,19, so on and so forth.


<!-- Sent from Reviewable.io -->

2021-06-20 21:41 UTC, ahmedsabie reviewed
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5233)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @lina128 and @pyu10055)

___
*[tfjs-backend-webgl/src/top_k_gpu.ts, line 32 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5233#-McVN6PbB8g7hKhT4wRu:-McfLk6v7UV-7oJBOmiU:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/a3cec8849c439ccf9cea6bde7ccc4dce93c57210/tfjs-backend-webgl/src/top_k_gpu.ts#L32)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

can you add jdoc for explaining the prameters, thanks
</blockquote></details>

Done.
___
*[tfjs-backend-webgl/src/top_k_gpu.ts, line 32 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5233#-McVs144D_LwobA-9xag:-McfM3wv48MSMXyX2Dzt:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/a3cec8849c439ccf9cea6bde7ccc4dce93c57210/tfjs-backend-webgl/src/top_k_gpu.ts#L32)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
> n
> ```
Can this be a uniform? Otherwise, for different n, there will be different shader created.
</blockquote></details>

Done.
___
*[tfjs-backend-webgl/src/top_k_gpu.ts, line 49 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5233#-McWLkA9005Wn-B_nj3l:-McfLqOC3nA1rlEIsjGx:b2hxt) ([raw file](https://github.com/tensorflow/tfjs/blob/a3cec8849c439ccf9cea6bde7ccc4dce93c57210/tfjs-backend-webgl/src/top_k_gpu.ts#L49)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
> // Maps both indices in a pair to the first index
> ```
As discussed offline, sugg annotation:
// We compare elements pair-wise within a group of size 2*inc. The comparing rule for each group alternates between ascending and descending. Within each group, we compare each pair at position i and i+inc. To decide whether an element at position i is x0 or x1, we mod it by 2*inc, if the result is smaller than inc, it is in the first half of the group, we denote it as x0, otherwise we denote it as x1. For example, as shown in the paper Figure5(a), element[1] is in the second half of the group when group size is 2, but it is in the first half of the group when group size is 4.
</blockquote></details>

Great annotation thank you!
___
*[tfjs-backend-webgl/src/top_k_gpu.ts, line 66 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5233#-McWTnD_D-CNEdnUsD4f:-McfM5h5BrJXhncEbY_z:bz1lteu) ([raw file](https://github.com/tensorflow/tfjs/blob/a3cec8849c439ccf9cea6bde7ccc4dce93c57210/tfjs-backend-webgl/src/top_k_gpu.ts#L66)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
> float(i0)
> ```
The output dtype is 'int32', do we need to convert to float here?
</blockquote></details>

setOuput only accepts float, i think its because older GLSL standards don't guarantee that ints are distinct types from floating point
___
*[tfjs-backend-webgl/src/top_k_gpu.ts, line 85 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5233#-McVNo2z70AwLVSNez2P:-McfLkXa9zvS16uBHrpJ:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/a3cec8849c439ccf9cea6bde7ccc4dce93c57210/tfjs-backend-webgl/src/top_k_gpu.ts#L85)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

`Number.NEGTIVE_INFINITY`?
</blockquote></details>

Done.
___
*[tfjs-backend-webgl/src/top_k_gpu.ts, line 97 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5233#-McVO-Aj0wA3AoPwAVBu:-McfLktiANoVYCnwDjCk:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/a3cec8849c439ccf9cea6bde7ccc4dce93c57210/tfjs-backend-webgl/src/top_k_gpu.ts#L97)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

can you add jdoc for explaining the prameters, thanks
</blockquote></details>

Done.
___
*[tfjs-backend-webgl/src/top_k_gpu.ts, line 111 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5233#-McZudyH6uiKxz2Ttol8:-McfMNDW9zwUd4-dtBzY:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/a3cec8849c439ccf9cea6bde7ccc4dce93c57210/tfjs-backend-webgl/src/top_k_gpu.ts#L111)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

This is how I understand it, let me know whether it's readable, we definitely need to add some annotations here:
The output size is half of the previous size. If the previous sequence is | | | |_ _ _ _ | | | | _ _ _ _  (k=4), we only need to output the indices at positions |, the indices at positions _ can be thrown away, see Figure5(b) After Phase2 (Merge phase) for example, we only need to output the orange bars. The output sequence should look like this 
| | | | | | | |. Because the sequence is halved, to map the output index back to the previous sequence to find the corresponding value, we need to *2. When we double the index, we basically interpolate a position, so 2i looks like | _ | _ | _ | _ | _ | _ | _. We move the | to the first k position of each 2k positions by `- elemIdx % k`. E.g. for output at index 4,5,6,7, we want to get the corresponding element at original index 8,9,10,11, for output at index 8,9,10,11, we want to get the corresponding element at original index 16,17,18,19, so on and so forth.
</blockquote></details>

Done.
___
*[tfjs-backend-webgl/src/kernels/TopK.ts, line 63 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5233#-McVJqf12TMujEtLBFG0:-McfMRRk483Gfb3Q29LO:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/a3cec8849c439ccf9cea6bde7ccc4dce93c57210/tfjs-backend-webgl/src/kernels/TopK.ts#L63)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[tfjs-backend-webgl/src/kernels/TopK.ts, line 73 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5233#-McWYbzPAqwCSEvraclq:-McfMZOx7ZpJ2Lii_k92:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/a3cec8849c439ccf9cea6bde7ccc4dce93c57210/tfjs-backend-webgl/src/kernels/TopK.ts#L73)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
>   const disposeIntermediateTensorInfoOrNull = (tensorInfo: TensorInfo) => {
>     if (tensorInfo !== null) {
>       backend.disposeIntermediateTensorInfo(tensorInfo);
>     }
>   };
> ```
Can you move this function outside of the current function?
</blockquote></details>

Done.
___
*[tfjs-backend-webgl/src/kernels/TopK.ts, line 80 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5233#-McWYGDB3WUNNaLYyn8c:-McfMZyY9tzQS1GYlNHT:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/a3cec8849c439ccf9cea6bde7ccc4dce93c57210/tfjs-backend-webgl/src/kernels/TopK.ts#L80)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
> inputs.length === 1
> ```
sugg code style: `inputs.length === 1 /* firstPass */`
</blockquote></details>

Done.
___
*[tfjs-backend-webgl/src/kernels/TopK.ts, line 96 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5233#-McWiU2104BWult_tQKJ:-McfM_Ur8RBqcC0zvoUH:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/a3cec8849c439ccf9cea6bde7ccc4dce93c57210/tfjs-backend-webgl/src/kernels/TopK.ts#L96)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
>  // Step 2: merge
> ```
Move this annotation to above the for loop.
</blockquote></details>

Done.
___
*[tfjs-backend-webgl/src/kernels/TopK.ts, line 99 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5233#-Mc_-1DSCcdj5pU8lsxr:-McfM_vqA4_Ly6MnYPEv:bmcjhgw) ([raw file](https://github.com/tensorflow/tfjs/blob/a3cec8849c439ccf9cea6bde7ccc4dce93c57210/tfjs-backend-webgl/src/kernels/TopK.ts#L99)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

> ```
> inputs.length === 1
> ```
Will this every be true for merge program, since the SwapProgram has been executed and indices will be not null anymore?
</blockquote></details>

If k = 1 then first stage swap doesn't run
___
*[tfjs-backend-webgl/src/kernels/TopK.t [...]

2021-06-21 15:17 UTC, pyu10055 requested changes
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5233)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @ahmedsabie, @lina128, and @pyu10055)

___
*[tfjs-backend-webgl/src/kernels/TopK.ts, line 68 at r2](https://reviewable.io/reviews/tensorflow/tfjs/5233#-Mcj88fD5Xuv72OKref8:-Mcj88fD5Xuv72OKref9:bgshilt) ([raw file](https://github.com/tensorflow/tfjs/blob/a8f005cc679f9462bcd42aa74c3b0d0f5ff388bd/tfjs-backend-webgl/src/kernels/TopK.ts#L68)):*
> ```XML
>   }
> 
>   // Reshape into a 2d tensor [batch, lastDim] and compute topk along lastDim.
> ```

Please take a look at the concat op how it execute the op on cpu shouldExecuteOnCPU is true for the inputs.
https://github.com/tensorflow/tfjs/blob/913e86ea3923a6530dcec4617ad8a369540889bc/tfjs-backend-webgl/src/kernels/Concat_impl.ts#L51


<!-- Sent from Reviewable.io -->

2021-06-21 16:14 UTC, lina128 reviewed
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5233)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @ahmedsabie, @lina128, and @pyu10055)

___
*[tfjs-backend-webgl/src/top_k_gpu.ts, line 47 at r2](https://reviewable.io/reviews/tensorflow/tfjs/5233#-McjLBgu7MUWOgDFB0dC:-McjLBgvCuM4lx5_05E3:b-h5iv3p) ([raw file](https://github.com/tensorflow/tfjs/blob/a8f005cc679f9462bcd42aa74c3b0d0f5ff388bd/tfjs-backend-webgl/src/top_k_gpu.ts#L47)):*
> ```
> firstPass: boolean
> ```
firstPass should probably be uniform too, otherwise, it always creates 2 shaders.


<!-- Sent from Reviewable.io -->

2021-06-21 17:50 UTC, lina128 approved these changes
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5233)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @ahmedsabie, @lina128, and @pyu10055)

___
*[tfjs-backend-webgl/src/top_k_gpu.ts, line 66 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5233#-McWTnD_D-CNEdnUsD4f:-McjLhQB39X2l_3JLb8O:bx40oul) ([raw file](https://github.com/tensorflow/tfjs/blob/a3cec8849c439ccf9cea6bde7ccc4dce93c57210/tfjs-backend-webgl/src/top_k_gpu.ts#L66)):*
<details><summary><i>Previously, ahmedsabie wrote…</i></summary><blockquote>

setOuput only accepts float, i think its because older GLSL standards don't guarantee that ints are distinct types from floating point
</blockquote></details>

Got it, thanks for the explanation!
___
*[tfjs-backend-webgl/src/top_k_gpu.ts, line 141 at r2](https://reviewable.io/reviews/tensorflow/tfjs/5233#-McjLwzH1pNs9SvGt4kV:-McjLwzH1pNs9SvGt4kW:boxwoaf) ([raw file](https://github.com/tensorflow/tfjs/blob/a8f005cc679f9462bcd42aa74c3b0d0f5ff388bd/tfjs-backend-webgl/src/top_k_gpu.ts#L141)):*
> ```
> firstPass: boolean
> ```
Make this a uniform too.
___
*[tfjs-backend-webgl/src/kernels/TopK.ts, line 135 at r2](https://reviewable.io/reviews/tensorflow/tfjs/5233#-McjMaxK4MP76TYX-X0m:-McjMaxK4MP76TYX-X0n:b-q57wm9) ([raw file](https://github.com/tensorflow/tfjs/blob/a8f005cc679f9462bcd42aa74c3b0d0f5ff388bd/tfjs-backend-webgl/src/kernels/TopK.ts#L135)):*
> ```XML
>   // Reshape back to the original input shape, except that the last
>   // dimension is k.
>   xShape[xShape.length - 1] = k;
> ```

Let's not mutate xShape, create a new one.


<!-- Sent from Reviewable.io -->

2021-06-21 19:08 UTC, ahmedsabie reviewed
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5233)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @ahmedsabie, @lina128, and @pyu10055)

___
*[tfjs-backend-webgl/src/top_k_gpu.ts, line 47 at r2](https://reviewable.io/reviews/tensorflow/tfjs/5233#-McjLBgu7MUWOgDFB0dC:-McjxIq01G9uLCB6rGHu:b-37uikx) ([raw file](https://github.com/tensorflow/tfjs/blob/a8f005cc679f9462bcd42aa74c3b0d0f5ff388bd/tfjs-backend-webgl/src/top_k_gpu.ts#L47)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
> firstPass: boolean
> ```
firstPass should probably be uniform too, otherwise, it always creates 2 shaders.
</blockquote></details>

With the current implementation firstPass can't be a uniform because when it's true there is no indices variable passed in so the getIndices call in WebGL won't compile, whereas firstPass here is used to modify the program pre compilation so that doesn't happen. The one fix I can think of is to pass in an empty indices when firstPass = true to the webGL program but just ignore its value, it's a bit confusing but I can add a commen, what do you think?
___
*[tfjs-backend-webgl/src/kernels/TopK.ts, line 68 at r2](https://reviewable.io/reviews/tensorflow/tfjs/5233#-Mcj88fD5Xuv72OKref8:-Mcjx8Gt4H1cNzA7oxG-:b-ru0xgc) ([raw file](https://github.com/tensorflow/tfjs/blob/a8f005cc679f9462bcd42aa74c3b0d0f5ff388bd/tfjs-backend-webgl/src/kernels/TopK.ts#L68)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

Please take a look at the concat op how it execute the op on cpu shouldExecuteOnCPU is true for the inputs.
https://github.com/tensorflow/tfjs/blob/913e86ea3923a6530dcec4617ad8a369540889bc/tfjs-backend-webgl/src/kernels/Concat_impl.ts#L51
</blockquote></details>

Done. Added above
___
*[tfjs-backend-webgl/src/kernels/TopK.ts, line 135 at r2](https://reviewable.io/reviews/tensorflow/tfjs/5233#-McjMaxK4MP76TYX-X0m:-McjxFBS-HbZbMZi3uqO:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/a8f005cc679f9462bcd42aa74c3b0d0f5ff388bd/tfjs-backend-webgl/src/kernels/TopK.ts#L135)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Let's not mutate xShape, create a new one.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-21 20:00 UTC, pyu10055 approved these changes
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5233)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @ahmedsabie and @lina128)



<!-- Sent from Reviewable.io -->

2021-06-21 20:12 UTC, lina128 reviewed
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5233)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @ahmedsabie and @lina128)

___
*[tfjs-backend-webgl/src/top_k_gpu.ts, line 47 at r2](https://reviewable.io/reviews/tensorflow/tfjs/5233#-McjLBgu7MUWOgDFB0dC:-MckBlZh1UWN2jtnNfpo:bp3umdw) ([raw file](https://github.com/tensorflow/tfjs/blob/a8f005cc679f9462bcd42aa74c3b0d0f5ff388bd/tfjs-backend-webgl/src/top_k_gpu.ts#L47)):*
<details><summary><i>Previously, ahmedsabie wrote…</i></summary><blockquote>

With the current implementation firstPass can't be a uniform because when it's true there is no indices variable passed in so the getIndices call in WebGL won't compile, whereas firstPass here is used to modify the program pre compilation so that doesn't happen. The one fix I can think of is to pass in an empty indices when firstPass = true to the webGL program but just ignore its value, it's a bit confusing but I can add a commen, what do you think?
</blockquote></details>

The fix sounds good.


<!-- Sent from Reviewable.io -->

2021-06-21 21:49 UTC, lina128 reviewed
LGTM! Can we benchmark the new implementation so that we have a sense how much time it improves?

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5233#-:-MckXqr01NdrHmIVzUrj:b-ycown7)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @ahmedsabie and @lina128)



<!-- Sent from Reviewable.io -->

2021-06-21 22:04 UTC, merged

2021-06-21 22:04 UTC, ahmedsabie commented
> LGTM! Can we benchmark the new implementation so that we have a sense how much time it improves?
> 
> > _[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5233#-:-MckXqr01NdrHmIVzUrj:b-ycown7)_ status: :shipit: complete! 2 of 1 approvals obtained (waiting on @ahmedsabie and @lina128)

Sounds good I'll do that next