Add notes for reviewing Bazel migration PRs
tensorflow/tfjs pull request #5680
Opened 2021-09-30 00:03 UTC by mattsoulanille

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

2021-09-30 17:12 UTC, pyu10055 approved these changes
thank you for the nice checklist.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5680#-:-MkrgEWO4a6j0HZ1Evlv:b5jt9zd)* status: :shipit: complete! 1 of 1 approvals obtained



<!-- Sent from Reviewable.io -->

2021-09-30 17:19 UTC, pyu10055 requested changes
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5680)* status: 0 of 1 approvals obtained (waiting on @mattsoulanille)

___
*[BAZEL_MIGRATION.md, line 428 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5680#-MkrhjDDEP2mzkSEXpgZ:-MkrhjDDEP2mzkSEXpg_:b-a0obsb) ([raw file](https://github.com/tensorflow/tfjs/blob/86d53616ec9245216713782cfc6bf14ff24bdf49/BAZEL_MIGRATION.md#L428)):*
> ```Markdown
> * For browser tests, it may be worth checking that all desired browser configurations will run in nightly CI.
> * Make sure browser tests include all required tests. The `enumerate_tests` rule is usually necessary to make the browser actually run tests.
> * If the build and tests are fully handled by Bazel and don't need any other cloudbuild steps, make sure the package's `cloudbuild.yml` file is removed and the package is removed from [scripts/package_dependencies.json](https://github.com/tensorflow/tfjs/blob/master/scripts/package_dependencies.json).
> ```

I think we need to make sure the steps in the cloudbuild.yml should be converted to bazel as much as we can.


<!-- Sent from Reviewable.io -->

2021-09-30 17:43 UTC, mattsoulanille reviewed
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5680)* status: 0 of 1 approvals obtained (waiting on @pyu10055)

___
*[BAZEL_MIGRATION.md, line 428 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5680#-MkrhjDDEP2mzkSEXpgZ:-MkrnFFy6SsvyJZBtNeg:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/86d53616ec9245216713782cfc6bf14ff24bdf49/BAZEL_MIGRATION.md#L428)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

I think we need to make sure the steps in the cloudbuild.yml should be converted to bazel as much as we can.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-10-01 17:10 UTC, pyu10055 approved these changes

2021-10-01 22:25 UTC, merged