[webgl]Add functions for parallel compilation
tensorflow/tfjs pull request #5826
Opened 2021-11-09 03:35 UTC by lina128

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

2021-11-09 03:40 UTC, lina128 commented
cc @qjia7

2021-11-16 04:50 UTC, pyu10055 requested changes
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5826)* status: 0 of 1 approvals obtained (waiting on @lina128)

___
*[tfjs-backend-webgl/src/backend_webgl.ts, line 1122 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5826#-Moae6Ui6tlpCTskFVrU:-Moae6Ui6tlpCTskFVrV:bk3cj00) ([raw file](https://github.com/tensorflow/tfjs/blob/32b8f1b829745e9e903cae3149115d10acffd8f5/tfjs-backend-webgl/src/backend_webgl.ts#L1122)):*
> ```XML
> 
>   async checkCompileCompletionAsync(): Promise<boolean[]> {
>     const ps = [];
> ```

rename to `promises`
___
*[tfjs-backend-webgl/src/backend_webgl.ts, line 1121 at r2](https://reviewable.io/reviews/tensorflow/tfjs/5826#-Mob2BGq1mRK3U2L5iLY:-Mob2BGq1mRK3U2L5iLZ:b-hlytty) ([raw file](https://github.com/tensorflow/tfjs/blob/9e5bfd675c272250346aae552f2d59db4ba017d3/tfjs-backend-webgl/src/backend_webgl.ts#L1121)):*
> ```XML
>     } else {
>       for (const [, binary] of Object.entries(this.binaryCache)) {
>         const p: Promise<boolean> = new Promise((resolve) => {
> ```

you can combine the array push with the creation of the promise.
___
*[tfjs-backend-webgl/src/backend_webgl_test.ts, line 759 at r2](https://reviewable.io/reviews/tensorflow/tfjs/5826#-Mob2fce8DbGY4btyqq9:-Mob2fce8DbGY4btyqqA:b-hfpv1m) ([raw file](https://github.com/tensorflow/tfjs/blob/9e5bfd675c272250346aae552f2d59db4ba017d3/tfjs-backend-webgl/src/backend_webgl_test.ts#L759)):*
> ```XML
>   // because it's a global flag, the async test will affect other tests.
>   it('does not have memory leak.', () => {
>     console.log('hello world');
> ```

remove?
___
*[tfjs-backend-webgl/src/backend_webgl_test.ts, line 778 at r2](https://reviewable.io/reviews/tensorflow/tfjs/5826#-Mob3vn6BZ9rOP3iL1FD:-Mob3vn6BZ9rOP3iL1FE:b-b3yhm3) ([raw file](https://github.com/tensorflow/tfjs/blob/9e5bfd675c272250346aae552f2d59db4ba017d3/tfjs-backend-webgl/src/backend_webgl_test.ts#L778)):*
> ```XML
>     expectArraysClose(data, [2, 2, 2]);
>     tf.dispose([a0, b0, c0]);
>     tf.removeBackend(customWebGLBackendName);
> ```

should we verify that after removing the backend, the getBinaryCache() call return 0 or the new backend starts with 0 ?
___
*[tfjs-backend-webgl/src/gpgpu_math.ts, line 49 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5826#-Mob0hlG9I-4MNPYfqGI:-Mob0hlG9I-4MNPYfqGJ:b-ebknr3) ([raw file](https://github.com/tensorflow/tfjs/blob/32b8f1b829745e9e903cae3149115d10acffd8f5/tfjs-backend-webgl/src/gpgpu_math.ts#L49)):*
> ```XML
> }
> 
> export interface GPGPUBinary {
> ```

should GPGPUBinary extends from GPGPUBinaryLocations interface?


<!-- Sent from Reviewable.io -->

2021-12-16 01:36 UTC, pyu10055 requested changes
> Reviewed 2 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5826)* status: 0 of 1 approvals obtained (waiting on @lina128)

___
*[tfjs-backend-webgl/src/backend_webgl.ts, line 835 at r3](https://reviewable.io/reviews/tensorflow/tfjs/5826#-Mr-p9mx14Y6Uzte3mBu:-Mr-p9mx14Y6Uzte3mBv:bbqzneq) ([raw file](https://github.com/tensorflow/tfjs/blob/bcea773056c946390d39f9a22667f92582da2435/tfjs-backend-webgl/src/backend_webgl.ts#L835)):*
> ```XML
>       // When in precompile phase, we want to precompile all the shaders, no
>       // matter whether texture is uploaded or not.
>       if (texData.texture != null || engine().state.compileOnly) {
> ```

it is not clear what is this condition for? the original code does check null for texture, if when compileOnly is true will need to execute the block, is it changing the behave for compileOnly is false?
___
*[tfjs-backend-webgl/src/backend_webgl_test.ts, line 798 at r3](https://reviewable.io/reviews/tensorflow/tfjs/5826#-Mr-sKyDES5tl0OvFkWv:-Mr-sKyDES5tl0OvFkWw:b-k1tjkj) ([raw file](https://github.com/tensorflow/tfjs/blob/bcea773056c946390d39f9a22667f92582da2435/tfjs-backend-webgl/src/backend_webgl_test.ts#L798)):*
> ```XML
> 
>     // Pre-compile round.
>     tf.engine().state.compileOnly = true;
> ```

Should this be a core flag that can be set like  `tf.env().set('ENGINE_COMPILE_ONLY', true)`?
___
*[tfjs-backend-webgl/src/gpgpu_math.ts, line 107 at r3](https://reviewable.io/reviews/tensorflow/tfjs/5826#-Mr-qrvOAeVNAHLyeIs5:-Mr-qrvOAeVNAHLyeIs6:b-5rqnoa) ([raw file](https://github.com/tensorflow/tfjs/blob/bcea773056c946390d39f9a22667f92582da2435/tfjs-backend-webgl/src/gpgpu_math.ts#L107)):*
> ```XML
> 
>   if (!engine().state.compileOnly) {
>     const {
> ```

you can use deconstrcution here?
```
const locations = getUniformLocations(gpgpu, program, webGLProgram);
return {program, fragmentShader, source, webGLProgram, ...locations};
```


<!-- Sent from Reviewable.io -->

2021-12-16 19:18 UTC, lina128 reviewed
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5826)* status: 0 of 1 approvals obtained (waiting on @lina128 and @pyu10055)

___
*[tfjs-backend-webgl/src/backend_webgl.ts, line 1122 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5826#-Moae6Ui6tlpCTskFVrU:-MprKJXl8qGWYdF99hnm:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/32b8f1b829745e9e903cae3149115d10acffd8f5/tfjs-backend-webgl/src/backend_webgl.ts#L1122)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

rename to `promises`
</blockquote></details>

Done.
___
*[tfjs-backend-webgl/src/backend_webgl.ts, line 1121 at r2](https://reviewable.io/reviews/tensorflow/tfjs/5826#-Mob2BGq1mRK3U2L5iLY:-MprKjuh8vJxq6aSZgKF:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/9e5bfd675c272250346aae552f2d59db4ba017d3/tfjs-backend-webgl/src/backend_webgl.ts#L1121)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

you can combine the array push with the creation of the promise.
</blockquote></details>

Done.
___
*[tfjs-backend-webgl/src/backend_webgl.ts, line 835 at r3](https://reviewable.io/reviews/tensorflow/tfjs/5826#-Mr-p9mx14Y6Uzte3mBu:-Mr3c_4H4bwzD08yaw6V:bas5cb8) ([raw file](https://github.com/tensorflow/tfjs/blob/bcea773056c946390d39f9a22667f92582da2435/tfjs-backend-webgl/src/backend_webgl.ts#L835)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

it is not clear what is this condition for? the original code does check null for texture, if when compileOnly is true will need to execute the block, is it changing the behave for compileOnly is false?
</blockquote></details>

This seems unnecessary, removed.
___
*[tfjs-backend-webgl/src/backend_webgl_test.ts, line 759 at r2](https://reviewable.io/reviews/tensorflow/tfjs/5826#-Mob2fce8DbGY4btyqq9:-MprKnWg1uWlpRb8N3X9:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/9e5bfd675c272250346aae552f2d59db4ba017d3/tfjs-backend-webgl/src/backend_webgl_test.ts#L759)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

remove?
</blockquote></details>

Done.
___
*[tfjs-backend-webgl/src/backend_webgl_test.ts, line 778 at r2](https://reviewable.io/reviews/tensorflow/tfjs/5826#-Mob3vn6BZ9rOP3iL1FD:-MprLCoc1WYTQRaY2CZx:b-4tn2tw) ([raw file](https://github.com/tensorflow/tfjs/blob/9e5bfd675c272250346aae552f2d59db4ba017d3/tfjs-backend-webgl/src/backend_webgl_test.ts#L778)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

should we verify that after removing the backend, the getBinaryCache() call return 0 or the new backend starts with 0 ?
</blockquote></details>

After removing the backend, we won't be able to call getBinaryCache() because the instance no longer exists. For the new backend, it's a new instance, it will start with 0.
___
*[tfjs-backend-webgl/src/gpgpu_math.ts, line 49 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5826#-Mob0hlG9I-4MNPYfqGI:-MprM-fR8lmW-FnK0Vs0:bymr6pq) ([raw file](https://github.com/tensorflow/tfjs/blob/32b8f1b829745e9e903cae3149115d10acffd8f5/tfjs-backend-webgl/src/gpgpu_math.ts#L49)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

should GPGPUBinary extends from GPGPUBinaryLocations interface?
</blockquote></details>

Ah, good idea, done.
___
*[tfjs-backend-webgl/src/gpgpu_math.ts, line 107 at r3](https://reviewable.io/reviews/tensorflow/tfjs/5826#-Mr-qrvOAeVNAHLyeIs5:-Mr3dhu00O20INxcKW1N:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/bcea773056c946390d39f9a22667f92582da2435/tfjs-backend-webgl/src/gpgpu_math.ts#L107)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

you can use deconstrcution here?
```
const locations = getUniformLocations(gpgpu, program, webGLProgram);
return {program, fragmentShader, source, webGLProgram, ...locations};
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-16 19:19 UTC, lina128 reviewed
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5826)* status: 0 of 1 approvals obtained (waiting on @pyu10055)

___
*[tfjs-backend-webgl/src/backend_webgl_test.ts, line 798 at r3](https://reviewable.io/reviews/tensorflow/tfjs/5826#-Mr-sKyDES5tl0OvFkWv:-Mr3fkeGEEj8CLhPJlG4:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/bcea773056c946390d39f9a22667f92582da2435/tfjs-backend-webgl/src/backend_webgl_test.ts#L798)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

Should this be a core flag that can be set like  `tf.env().set('ENGINE_COMPILE_ONLY', true)`?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-16 19:35 UTC, pyu10055 approved these changes
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5826)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @lina128 and @pyu10055)

___
*[tfjs-core/src/engine.ts, line 159 at r4](https://reviewable.io/reviews/tensorflow/tfjs/5826#-Mr3jVcDDO0cD2AnvHFv:-Mr3jVcE9mZJyuHoAaoa:b53td0f) ([raw file](https://github.com/tensorflow/tfjs/blob/bf60cfd818cccb00bd977a7dc87adee3da377d86/tfjs-core/src/engine.ts#L159)):*
> ```XML
>   };
> 
>   compileOnly = false;
> ```

is this variable still needed?


<!-- Sent from Reviewable.io -->

2021-12-16 20:39 UTC, lina128 reviewed
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5826)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @pyu10055)

___
*[tfjs-core/src/engine.ts, line 159 at r4](https://reviewable.io/reviews/tensorflow/tfjs/5826#-Mr3jVcDDO0cD2AnvHFv:-Mr3yD1X9h2R-5HFYgbo:btquzjz) ([raw file](https://github.com/tensorflow/tfjs/blob/bf60cfd818cccb00bd977a7dc87adee3da377d86/tfjs-core/src/engine.ts#L159)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

is this variable still needed?
</blockquote></details>

Good catch, removed.


<!-- Sent from Reviewable.io -->

2022-01-20 13:14 UTC, vladmandic commented
Has this PR stalled? I was looking forward to this improvement a lot.

2022-03-16 00:55 UTC, merged