Fix bufferSync return type
tensorflow/tfjs pull request #6362
Opened 2022-05-02 20:30 UTC by ahmedsabie

The existing bufferSync always returned a float template type which throws away the type, so users of the function always assume they are working with a number array which is incorrect for string types.

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

2022-05-02 21:11 UTC, pyu10055 approved these changes
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6362)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @lina128)



<!-- Sent from Reviewable.io -->

2022-05-03 00:15 UTC, lina128 requested changes
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6362)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @ahmedsabie)

___
*[`tfjs-backend-cpu/src/backend_cpu.ts` line 150 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6362#-N16GC1q3i3xBveiqPTt:-N16GC1q3i3xBveiqPTu:b-wyaz77) ([raw file](https://github.com/tensorflow/tfjs/blob/e04514eeac2689e53d6c6a91cddc23fd3c3de2d0/tfjs-backend-cpu/src/backend_cpu.ts#L150)):*
> ```XML
>   }
> 
>   bufferSync<R extends Rank, D extends DataType>(t: TensorInfo):
> ```

Can you add 'float32' as the default DataType here?



_Code quote:_
```XML
D 
```


<!-- Sent from Reviewable.io -->

2022-05-03 21:59 UTC, lina128 reviewed
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6362)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @ahmedsabie)

___
*[`tfjs-backend-cpu/src/backend_cpu.ts` line 150 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6362#-N16GC1q3i3xBveiqPTt:-N1AvoIa51YtppboQrtf:b7pawlf) ([raw file](https://github.com/tensorflow/tfjs/blob/e04514eeac2689e53d6c6a91cddc23fd3c3de2d0/tfjs-backend-cpu/src/backend_cpu.ts#L150)):*
<details><summary><i>Previously, ahmedsabie wrote…</i></summary><blockquote>

This would reintroduce the problem of accidental cast to float since no compiler error would be generated, versus without default where you have to assert the default so it's an explicit decision. This is the same problem I ran into trying to add string support to SparseToDense
</blockquote></details>

Can you specify what error you saw when adding string support to SparseToDense? Or maybe send me that PR with the CI log? Thanks


<!-- Sent from Reviewable.io -->

2022-05-04 19:21 UTC, ahmedsabie reviewed
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6362)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @lina128)

___
*[`tfjs-backend-cpu/src/backend_cpu.ts` line 150 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6362#-N16GC1q3i3xBveiqPTt:-N1FPangEa9Jxo4s4p_g:b-spgvua) ([raw file](https://github.com/tensorflow/tfjs/blob/e04514eeac2689e53d6c6a91cddc23fd3c3de2d0/tfjs-backend-cpu/src/backend_cpu.ts#L150)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Can you specify what error you saw when adding string support to SparseToDense? Or maybe send me that PR with the CI log? Thanks
</blockquote></details>

The error involved defaultValue being type asserted into a number which compiled due to bufferSync always returning a float32 dtype implicitly. That's when I found this bug with bufferSync storing string values as a float32 dtype so that's why we need dtype template added.

I suggest we don't put a default because it forces the user to choose what type they are working with and it is explicit to the next user. The same problem above would occur if the default was float32 and the previous coder didn't explicitly specify float


<!-- Sent from Reviewable.io -->

2022-05-09 23:41 UTC, lina128 reviewed
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6362)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @ahmedsabie and @lina128)

___
*[`tfjs-backend-cpu/src/backend_cpu.ts` line 158 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6362#-N1fBJ_j6S8EteeGOPPk:-N1fBJ_j6S8EteeGOPPl:b3kljvr) ([raw file](https://github.com/tensorflow/tfjs/blob/e04514eeac2689e53d6c6a91cddc23fd3c3de2d0/tfjs-backend-cpu/src/backend_cpu.ts#L158)):*
> ```XML
>         const strings = (data as Uint8Array[]).map(d => util.decodeString(d));
>         return buffer(t.shape as ShapeMap[R], t.dtype, strings) as
>             TensorBuffer<R, D>;
> ```

Will it throw error if we force cast type as string here and just use default everywhere else? Like this:
```
        return buffer(t.shape as ShapeMap[R], t.dtype, strings) as
            TensorBuffer<R, string>;

or

        return buffer(t.shape as ShapeMap[R], t.dtype, strings) as
            any as TensorBuffer<R, string>;


```



_Code quote:_
```XML
TensorBuffer<R, D>
```


<!-- Sent from Reviewable.io -->

2022-05-11 17:44 UTC, ahmedsabie reviewed
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6362)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @lina128)

___
*[`tfjs-backend-cpu/src/backend_cpu.ts` line 158 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6362#-N1fBJ_j6S8EteeGOPPk:-N1oCQYpBjA3J9Z0mZgm:b7eqph6) ([raw file](https://github.com/tensorflow/tfjs/blob/e04514eeac2689e53d6c6a91cddc23fd3c3de2d0/tfjs-backend-cpu/src/backend_cpu.ts#L158)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Will it throw error if we force cast type as string here and just use default everywhere else? Like this:
```
        return buffer(t.shape as ShapeMap[R], t.dtype, strings) as
            TensorBuffer<R, string>;

or

        return buffer(t.shape as ShapeMap[R], t.dtype, strings) as
            any as TensorBuffer<R, string>;


```
</blockquote></details>

It's a compile error because templates are inputs, the user could theoretically pass in a string input but ask for a float return type which is why you can't make an assertion to string


<!-- Sent from Reviewable.io -->

2022-05-11 18:07 UTC, lina128 approved these changes
LGTM

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6362#-:-N1oING96rtCVPCmDpmR:bb6ywmx)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @lina128)



<!-- Sent from Reviewable.io -->

2022-05-11 18:42 UTC, merged