[core] Add a synchronous I/O handler
tensorflow/tfjs pull request #6417
Opened 2022-05-17 22:55 UTC by mattsoulanille

Add IOHandlerSync, which has the same interface as IOHandler but returns values instead of promises. Add fromMemorySync, the synchronous version of fromMemory, and withSaveHandlerSync, the synchronous version of withSavehandler.

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

2022-05-17 22:58 UTC, mattsoulanille reviewed
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6417)* status: 0 of 1 approvals obtained (waiting on @lina128 and @pyu10055)

___
*[`tfjs-core/src/io/passthrough_test.ts` line 268 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6417#-N2JEJDh8YZD6vu2FEiU:-N2JEJDh8YZD6vu2FEiV:b4q66re) ([raw file](https://github.com/tensorflow/tfjs/blob/f7367a7488ca7702959a50e43078fb1ca4d46973/tfjs-core/src/io/passthrough_test.ts#L268)):*
> ```XML
>     expect(modelArtifacts.weightSpecs).toEqual(weightSpecs1);
>     expect(modelArtifacts.weightData).toEqual(weightData1);
>     expect(modelArtifacts.userDefinedMetadata).toEqual(userDefinedMetadata);
> ```

I would have preferred not to copy these tests from the async version, but I couldn't find a way to avoid it (couldn't easily use a variable to switch between sync and async). If you have any ideas about how to avoid this, please let me know.



_Code quote:_
```XML
describeWithFlags('Passthrough Loader Sync', BROWSER_ENVS, () => {
  it('load topology and weights: legacy signature', () => {
    const passthroughHandler =
        tf.io.fromMemorySync(modelTopology1, weightSpecs1, weightData1);
    const modelArtifacts = passthroughHandler.load();
    expect(modelArtifacts.modelTopology).toEqual(modelTopology1);
    expect(modelArtifacts.weightSpecs).toEqual(weightSpecs1);
    expect(modelArtifacts.weightData).toEqual(weightData1);
    expect(modelArtifacts.userDefinedMetadata).toEqual(undefined);
  });

  it('load topology and weights', () => {
    const passthroughHandler = tf.io.fromMemorySync({
      modelTopology: modelTopology1,
      weightSpecs: weightSpecs1,
      weightData: weightData1
    });
    const modelArtifacts = passthroughHandler.load();
    expect(modelArtifacts.modelTopology).toEqual(modelTopology1);
    expect(modelArtifacts.weightSpecs).toEqual(weightSpecs1);
    expect(modelArtifacts.weightData).toEqual(weightData1);
    expect(modelArtifacts.userDefinedMetadata).toEqual(undefined);
  });

  it('load model topology only: legacy signature', () => {
    const passthroughHandler = tf.io.fromMemorySync(modelTopology1);
    const modelArtifacts = passthroughHandler.load();
    expect(modelArtifacts.modelTopology).toEqual(modelTopology1);
    expect(modelArtifacts.weightSpecs).toEqual(undefined);
    expect(modelArtifacts.weightData).toEqual(undefined);
    expect(modelArtifacts.userDefinedMetadata).toEqual(undefined);
  });

  it('load model topology only', () => {
    const passthroughHandler =
        tf.io.fromMemorySync({modelTopology: modelTopology1});
    const modelArtifacts = passthroughHandler.load();
    expect(modelArtifacts.modelTopology).toEqual(modelTopology1);
    expect(modelArtifacts.weightSpecs).toEqual(undefined);
    expect(modelArtifacts.weightData).toEqual(undefined);
    expect(modelArtifacts.userDefinedMetadata).toEqual(undefined);
  });

  it('load topology, weights, and user-defined metadata', () => {
    const userDefinedMetadata: {} = {'fooField': 'fooValue'};
    const passthroughHandler = tf.io.fromMemorySync({
      modelTopology: modelTopology1,
      weightSpecs: weightSpecs1,
      weightData: weightData1,
      userDefinedMetadata
    });
    const modelArtifacts = passthroughHandler.load();
    expect(modelArtifacts.modelTopology).toEqual(modelTopology1);
    expect(modelArtifacts.weightSpecs).toEqual(weightSpecs1);
    expect(modelArtifacts.weightData).toEqual(weightData1);
    expect(modelArtifacts.userDefinedMetadata).toEqual(userDefinedMetadata);
  });
});
```


<!-- Sent from Reviewable.io -->

2022-05-18 04:04 UTC, pyu10055 requested changes
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6417)* status: 0 of 1 approvals obtained (waiting on @lina128 and @mattsoulanille)

___
*[`tfjs-core/src/io/passthrough.ts` line 32 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6417#-N2JOv4C0kBSoNIl1kEs:-N2JOv4C0kBSoNIl1kEt:bev40nv) ([raw file](https://github.com/tensorflow/tfjs/blob/f7367a7488ca7702959a50e43078fb1ca4d46973/tfjs-core/src/io/passthrough.ts#L32)):*
> ```XML
> }
> 
> class PassthroughSaver<R extends SaveResult | Promise<SaveResult>> {
> ```

should we separate this class into sync and async versions?
___
*[`tfjs-core/src/io/passthrough.ts` line 98 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6417#-N2KHUCh5DNbyzBhyklS:-N2KHUCh5DNbyzBhyklT:bg0gc56) ([raw file](https://github.com/tensorflow/tfjs/blob/f7367a7488ca7702959a50e43078fb1ca4d46973/tfjs-core/src/io/passthrough.ts#L98)):*
> ```XML
>  * @param modelArtifacts a object containing model topology (i.e., parsed from
>  *   the JSON format).
>  * @param weightSpecs An array of `WeightsManifestEntry` objects describing the
> ```

optional?
___
*[`tfjs-core/src/io/passthrough.ts` line 100 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6417#-N2KHVm51LcwbL8ErdjD:-N2KHVm51LcwbL8ErdjE:bg0gc56) ([raw file](https://github.com/tensorflow/tfjs/blob/f7367a7488ca7702959a50e43078fb1ca4d46973/tfjs-core/src/io/passthrough.ts#L100)):*
> ```XML
>  * @param weightSpecs An array of `WeightsManifestEntry` objects describing the
>  *   names, shapes, types, and quantization of the weight data.
>  * @param weightData A single `ArrayBuffer` containing the weight data,
> ```

optional?
___
*[`tfjs-core/src/io/passthrough_test.ts` line 268 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6417#-N2JEJDh8YZD6vu2FEiU:-N2KIktK7MMocMpoSXZT:b-fy1ao3) ([raw file](https://github.com/tensorflow/tfjs/blob/f7367a7488ca7702959a50e43078fb1ca4d46973/tfjs-core/src/io/passthrough_test.ts#L268)):*
<details><summary><i>Previously, mattsoulanille (Matthew Soulanille) wrote…</i></summary><blockquote>

I would have preferred not to copy these tests from the async version, but I couldn't find a way to avoid it (couldn't easily use a variable to switch between sync and async). If you have any ideas about how to avoid this, please let me know.
</blockquote></details>

I think it is fine to have test copied, it will better to have verbose tests.
___
*[`tfjs-core/src/io/types.ts` line 390 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6417#-N2KJhTi8XYk5CeCsEz2:-N2KJhTi8XYk5CeCsEz3:b92h347) ([raw file](https://github.com/tensorflow/tfjs/blob/f7367a7488ca7702959a50e43078fb1ca4d46973/tfjs-core/src/io/types.ts#L390)):*
> ```XML
> }
> 
> export type Syncify<T> = T extends (...args: infer Args) => Promise<infer R>
> ```

can you explain what is this trying to accomplish?


<!-- Sent from Reviewable.io -->

2022-05-18 16:27 UTC, mattsoulanille reviewed
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6417)* status: 0 of 1 approvals obtained (waiting on @lina128 and @pyu10055)

___
*[`tfjs-core/src/io/passthrough.ts` line 32 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6417#-N2JOv4C0kBSoNIl1kEs:-N2MwSOE4glSzW2_dWLZ:b-kjf3ln) ([raw file](https://github.com/tensorflow/tfjs/blob/f7367a7488ca7702959a50e43078fb1ca4d46973/tfjs-core/src/io/passthrough.ts#L32)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

should we separate this class into sync and async versions?
</blockquote></details>

We could, but I don't think it's necessary, since the return type depends entirely on what the `saveHandler` passed to the class returns (The restriction that `R extends SaveResult | Promise<SaveResult>` could even be removed, but that's probably not a good idea). Splitting it into two classes would result in two copies of this code.
___
*[`tfjs-core/src/io/passthrough.ts` line 98 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6417#-N2KHUCh5DNbyzBhyklS:-N2MyZWEChAApMkZdnu5:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/f7367a7488ca7702959a50e43078fb1ca4d46973/tfjs-core/src/io/passthrough.ts#L98)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

optional?
</blockquote></details>

Done.
___
*[`tfjs-core/src/io/passthrough.ts` line 100 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6417#-N2KHVm51LcwbL8ErdjD:-N2MyZoy5XcucaYMrxT4:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/f7367a7488ca7702959a50e43078fb1ca4d46973/tfjs-core/src/io/passthrough.ts#L100)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

optional?
</blockquote></details>

Done.
___
*[`tfjs-core/src/io/passthrough_test.ts` line 268 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6417#-N2JEJDh8YZD6vu2FEiU:-N2MybZ2BhrNAzUrnAuz:brxp9sd) ([raw file](https://github.com/tensorflow/tfjs/blob/f7367a7488ca7702959a50e43078fb1ca4d46973/tfjs-core/src/io/passthrough_test.ts#L268)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

I think it is fine to have test copied, it will better to have verbose tests.
</blockquote></details>

Sounds good!
___
*[`tfjs-core/src/io/types.ts` line 390 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6417#-N2KJhTi8XYk5CeCsEz2:-N2Myemj8t2AVDAPs5yW:bpybtq) ([raw file](https://github.com/tensorflow/tfjs/blob/f7367a7488ca7702959a50e43078fb1ca4d46973/tfjs-core/src/io/types.ts#L390)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

can you explain what is this trying to accomplish?
</blockquote></details>

This type takes a function type that returns a promise. It returns a new type which is a function with the same arguments, but which returns a value instead of a promise.

e.g.
```
type Foo = (bar: number, baz: string) => Promise<[number, string]>;
type FooSync = Syncify<Foo>;
const fooSyncImpl: FooSync = (bar: number, baz: string) => [bar, baz];
```

It's mapped over the IOHandler to create the IOHandlerSync type. It isn't used anywhere else, so I've made it private to this file.


<!-- Sent from Reviewable.io -->

2022-05-18 18:53 UTC, lina128 approved these changes
LGTM. Address Ping's comments before merging.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6417#-:-N2NVzJMBwB2mwAYSDGM:b9cvy7t)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @pyu10055)



<!-- Sent from Reviewable.io -->

2022-05-18 23:29 UTC, pyu10055 requested changes
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6417)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @mattsoulanille and @pyu10055)

___
*[`tfjs-core/src/io/types.ts` line 390 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6417#-N2KJhTi8XYk5CeCsEz2:-N2OUuKmBBMjw0MCkHA6:b3sdkjn) ([raw file](https://github.com/tensorflow/tfjs/blob/f7367a7488ca7702959a50e43078fb1ca4d46973/tfjs-core/src/io/types.ts#L390)):*
<details><summary><i>Previously, mattsoulanille (Matthew Soulanille) wrote…</i></summary><blockquote>

This type takes a function type that returns a promise. It returns a new type which is a function with the same arguments, but which returns a value instead of a promise.

e.g.
```
type Foo = (bar: number, baz: string) => Promise<[number, string]>;
type FooSync = Syncify<Foo>;
const fooSyncImpl: FooSync = (bar: number, baz: string) => [bar, baz];
```

It's mapped over the IOHandler to create the IOHandlerSync type. It isn't used anywhere else, so I've made it private to this file.
</blockquote></details>

cool, why you would support other type and return never? Why not only allows T extends from the function type?


<!-- Sent from Reviewable.io -->

2022-05-19 00:24 UTC, pyu10055 approved these changes
> Reviewed 2 of 4 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6417)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @pyu10055)



<!-- Sent from Reviewable.io -->

2022-05-19 00:28 UTC, merged