Resizing layer and associated unit tests implemented (#33)
tensorflow/tfjs pull request #6858
Opened 2022-09-26 22:40 UTC by koyykdy

* Rescaling Preprocessing Layer Co-authored-by:
David Kim (@koyykdy) <dok098@ucsd.edu>
Brian Zheng (@brianzheng123) <brianzheng345@gmail.com>

* Version issues resolved

* linting and PR issues resolved
Co-authored-by: Adam Lang (@AdamLang96) <adamglang96@gmail.com>
Co-authored-by: (@Brianzheng123) <brianzheng345@gmail.com>

* initial implementation of image preprocessing: resizing layer, and associated unit tests. Comments and refactoring for image scaling layer

* License refactoring in computeOutputShape for image resizing layer

* Unit tests for image resizing preprocessing layer expanded and refactored

* refactored unit tests for resizing layer

* Preprocessing-Resizing layer unit test expansion and refactoring.
Co-authored-by: Adam Lang (@AdamLang96) <adamglang96@gmail.com>

* cleaning up commit diffs

Co-authored-by: AdamLang96 <45542095+AdamLang96@users.noreply.github.com>

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

2022-09-26 22:45 UTC, koyykdy commented
IMPORT NOTE:
The lower-level op implementation of image resizing-nearest neighbor in TensorFlow.js differs from the implementation of the comparable op in Keras-Python.

While the Python version of the op function always selects the bottom right cell of the sub-matrix to be used as the representative value of that region in the downscaled matrix, the JavaScript implementation defaults to the top left cell of the sub-matrix, and then preferentially shifts to the right side of the sub-matrix in all sub-matrices past the lateral halfway point ( calculated by floor((length-1)/2) ), and the bottom side of the sub-matrix in all sub-matrices past the vertical halfway point, when considering the top-left side of the parent matrix as the origin.

This causes a slight variation in the output values from nearest neighbor downscaling between the Python and JavaScript versions of the code as it currently stands, and the unit tests for the resizing layer has been implemented to reflect this difference in op-function behavior.

2022-09-28 18:01 UTC, mattsoulanille requested changes
Thanks for the PR! Sorry it took me a while to get to. I have just a few small changes.

2022-09-29 16:50 UTC, koyykdy commented on tfjs-layers/src/layers/preprocessing/image_resizing_test.ts
> +        randomNormal([height, width, numChannels]);
Requested changes have been commit in https://github.com/tensorflow/tfjs/pull/6858/commits/8532991569e1495c78344a4d26ef2fc688ab4715

2022-09-29 17:33 UTC, mattsoulanille approved these changes
LGTM with some small nits.

@ahmedsabie This PR is ready for your review when you get a chance. Thanks!

2022-09-29 17:33 UTC, mattsoulanille commented on tfjs-layers/src/layers/preprocessing/image_resizing_test.ts
> +    const inputTensor = tensor(inputArr, [height, width, numChannels]);
Nit: [`tf.range`](https://js.tensorflow.org/api/latest/#range) and [`tf.reshape`](https://js.tensorflow.org/api/latest/#reshape) can make this simpler.

```suggestion
    const rangeTensor = range(0, height * width);
    const inputTensor = reshape(rangeTensor, [height, width, numChannels]);
```

2022-09-29 17:33 UTC, mattsoulanille commented on tfjs-layers/src/layers/preprocessing/image_resizing.ts
> +        throw new Error(`mode is ${this.interpolation} but only ${[...INTERPOLATION_METHODS]} are supported`);
Nit: Sorry, my last suggestion forgot to include interpolation.
```suggestion
        throw new Error(`Interpolation is ${this.interpolation} but only ${[...INTERPOLATION_METHODS]} are supported`);
```

2022-09-29 17:35 UTC, mattsoulanille commented on tfjs-layers/src/layers/preprocessing/image_resizing_test.ts
> +    const inputTensor = tensor(inputArr, [height, width, numChannels]);
It looks like this applies to several other tests as well. Sorry I didn't catch this in my first review.

2022-09-29 18:09 UTC, closed without merging