Add kernel RaggedRange for CPU and WebGL backend
tensorflow/tfjs pull request #6871
Opened 2022-09-28 18:17 UTC by ahmedsabie

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

2022-09-28 18:27 UTC, mattsoulanille requested changes
Just a quick review removing "all rights reserved" from the license headers of new files (don't change existing files).

2022-09-28 18:27 UTC, mattsoulanille commented on tfjs-backend-cpu/src/kernels/RaggedRange.ts
> + * Copyright 2022 Google LLC. All Rights Reserved.
```suggestion
 * Copyright 2022 Google LLC.
```

2022-09-28 18:27 UTC, mattsoulanille commented on tfjs-backend-cpu/src/kernels/RaggedRange_impl.ts
> + * Copyright 2022 Google LLC. All Rights Reserved.
```suggestion
 * Copyright 2022 Google LLC.
```

2022-09-28 18:27 UTC, mattsoulanille commented on tfjs-backend-webgl/src/kernels/RaggedRange.ts
> + * Copyright 2022 Google LLC. All Rights Reserved.
```suggestion
 * Copyright 2022 Google LLC.
```

2022-09-28 18:27 UTC, mattsoulanille commented on tfjs-core/src/ops/ragged_range.ts
> + * Copyright 2022 Google LLC. All Rights Reserved.
```suggestion
 * Copyright 2022 Google LLC.
```

2022-09-28 18:27 UTC, mattsoulanille commented on tfjs-core/src/ops/ragged_range_test.ts
> + * Copyright 2022 Google LLC. All Rights Reserved.
```suggestion
 * Copyright 2022 Google LLC.
```

2022-09-28 21:11 UTC, lina128 approved these changes
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6871)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @ahmedsabie and @pyu10055)

___
*[`tfjs-backend-cpu/src/kernels/RaggedRange_impl.ts` line 20 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6871#-ND4vvLzBewnOj1ILAUz:-ND4vvLzBewnOj1ILAV-:b-mzonpm) ([raw file](https://github.com/tensorflow/tfjs/blob/a515495cf6009d4c88b583c318647923a4cf0a1b/tfjs-backend-cpu/src/kernels/RaggedRange_impl.ts#L20)):*
> ```XML
> import {DataType, TypedArray, util} from '@tensorflow/tfjs-core';
> 
> const INT32_MAX = 2147483647;
> ```

Why not use Number.MAX_SAFE_INTEGER?



_Code quote:_
```XML
const INT32_MAX = 2147483647
```


<!-- Sent from Reviewable.io -->

2022-09-30 23:21 UTC, pyu10055 approved these changes
thank you for adding this op.

> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6871#-:-NDFh3Jh3kU0VfVjkc0K:b5jbvdj)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @ahmedsabie)



<!-- Sent from Reviewable.io -->

2022-10-09 01:16 UTC, mattsoulanille approved these changes
LGTM

2022-10-10 17:30 UTC, merged