CenterCrop Layer
tensorflow/tfjs pull request #6875
Opened 2022-09-28 21:13 UTC by AdamLang96

* Center Crop Preprocessing Layer Co-authored-by:
David Kim (@koyykdy) <dok098@ucsd.edu>
Brian Zheng (@brianzheng123) <brianzheng345@gmail.com>

2022-09-29 21:38 UTC, AdamLang96 commented
@mattsoulanille Please take a look whenever you're available. Thanks!

2022-10-01 00:10 UTC, AdamLang96 commented
Hi @mattsoulanille,

Thanks again for meeting with us this morning! After reviewing the feedback on our last two layers, I am pretty confident we have some repeated mistakes in this one. @koyykdy and I will review this layer and ping you once we have cleaned those up to try and make things easier on your end, so don't worry about reviewing it for now.

Thanks,

Adam

2022-10-01 06:23 UTC, mattsoulanille commented
Thanks for letting me know, @AdamLang96. I'll wait for your ping.

2022-10-04 18:21 UTC, AdamLang96 commented
@mattsoulanille I think this is ready for review whenever you're available. Thank you!

2022-10-04 19:44 UTC, mattsoulanille requested changes
The logic looks good. I just have a few style changes. Thanks!

2022-10-04 19:44 UTC, mattsoulanille commented on tfjs-layers/src/layers/preprocessing/center_crop.ts
> +    const boxInd: Tensor1D = tensor([...Array(boxesArr.length).keys()],
Use [`tf.range`](https://js.tensorflow.org/api/latest/#range) instead.

2022-10-05 23:50 UTC, AdamLang96 commented on tfjs-layers/src/layers/preprocessing/center_crop.ts
> +    const inputWidth = inputShape[wAxis];
@mattsoulanille I may be wrong but I believe `Array.at()` is only available for TypeScript `4.6>` and `tfjs` is currently running `3.5.3`

2022-10-05 23:52 UTC, AdamLang96 commented
@mattsoulanille I updated the layer to reflect your changes. Let me know what you think. Thanks!

2022-10-06 20:21 UTC, mattsoulanille approved these changes
LGTM. Thanks!

2022-10-11 20:12 UTC, ahmedsabie requested changes

2022-10-11 20:12 UTC, ahmedsabie commented on tfjs-layers/src/layers/preprocessing/center_crop.ts
> +      let rank3      = false;
Can you rename to isRank3

2022-10-11 20:53 UTC, AdamLang96 commented on tfjs-layers/src/layers/preprocessing/center_crop.ts
> +      let rank3      = false;
@ahmedsabie done!

2022-10-11 23:09 UTC, mattsoulanille commented
This is failing `tslint`:
```
$ tslint -p tsconfig_tslint.json
/workspace/tfjs-layers/src/exports_layers.ts:1770:1
ERROR: 1770:1  jsdoc-format  asterisks in jsdoc must be aligned
ERROR: 1771:1  jsdoc-format  asterisks in jsdoc must be aligned
ERROR: 1772:1  jsdoc-format  asterisks in jsdoc must be aligned
ERROR: 1773:1  jsdoc-format  asterisks in jsdoc must be aligned
ERROR: 1774:1  jsdoc-format  asterisks in jsdoc must be aligned
ERROR: 1775:1  jsdoc-format  asterisks in jsdoc must be aligned
ERROR: 1776:1  jsdoc-format  asterisks in jsdoc must be aligned
ERROR: 1777:1  jsdoc-format  asterisks in jsdoc must be aligned
ERROR: 1778:1  jsdoc-format  asterisks in jsdoc must be aligned
ERROR: 1779:1  jsdoc-format  asterisks in jsdoc must be aligned
ERROR: 1780:1  jsdoc-format  asterisks in jsdoc must be aligned
ERROR: 1781:1  jsdoc-format  asterisks in jsdoc must be aligned
ERROR: 1782:1  jsdoc-format  asterisks in jsdoc must be aligned
ERROR: 1783:1  jsdoc-format  asterisks in jsdoc must be aligned
ERROR: 1784:1  jsdoc-format  asterisks in jsdoc must be aligned
ERROR: 1785:1  jsdoc-format  asterisks in jsdoc must be aligned
ERROR: 1786:1  jsdoc-format  asterisks in jsdoc must be aligned
ERROR: 1787:1  jsdoc-format  asterisks in jsdoc must be aligned
ERROR: 1788:1  jsdoc-format  asterisks in jsdoc must be aligned
ERROR: 1789:1  jsdoc-format  asterisks in jsdoc must be aligned
ERROR: 1790:1  jsdoc-format  asterisks in jsdoc must be aligned
```

2022-10-11 23:11 UTC, AdamLang96 commented
@mattsoulanille whoops just fixed it

2022-10-11 23:44 UTC, mattsoulanille commented
Thanks!
@ahmedsabie Please take another look.

2022-10-13 17:30 UTC, ahmedsabie approved these changes

2022-10-13 19:23 UTC, merged