Add script to launch tfjs debugger local server
tensorflow/tfjs pull request #7047
Opened 2022-11-14 18:42 UTC by jinjingforever

The script will pull the zip bundle from cloud storage, unzip it, and serve its files from memory. It also serves other files from the tfjs repo.

The script is supposed to be run from the root of the tfjs repo.

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

2022-11-14 19:14 UTC, mattsoulanille approved these changes
LGTM with a tiny nit.

2022-11-14 19:56 UTC, jinjingforever commented on package.json
> +    "adm-zip": "0.5.9",
Good know! Done. Thank you!

2022-11-14 22:09 UTC, pyu10055 requested changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/7047)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @jinjingforever and @mattsoulanille)

___
*[`scripts/start_local_debugger_server.js` line 23 at r3](https://reviewable.io/reviews/tensorflow/tfjs/7047#-NGsAh3B6c3lmkuxwnCC:-NGsAh3B6c3lmkuxwnCD:b7b3ze9) ([raw file](https://github.com/tensorflow/tfjs/blob/3c79fabfcacf9cb78635de3306dcad4687e214ce/scripts/start_local_debugger_server.js#L23)):*
> ```JavaScript
> 
> const TFJS_DEBUGGER_BUNDLE_URL =
>     'https://storage.googleapis.com/tfweb/tfjs-debugger-bundle/tfjs-debugger_20221111-105432.zip';
> ```

does cloud storage allow symlink? can we have a something like
`tfjs-debugger-bundle/tfjs-debugger_latest.zip` that allows the script to use the latest build?
or should the arg parser be able to parse command line version?


<!-- Sent from Reviewable.io -->

2022-11-14 22:31 UTC, pyu10055 reviewed
LGTM with a nit as well.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/7047#-:-NGsG4ks0YIS5594J69X:b-c9xz4l)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @jinjingforever and @mattsoulanille)



<!-- Sent from Reviewable.io -->

2022-11-17 20:11 UTC, jinjingforever reviewed
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/7047)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @mattsoulanille and @pyu10055)

___
*[`scripts/start_local_debugger_server.js` line 23 at r3](https://reviewable.io/reviews/tensorflow/tfjs/7047#-NGsAh3B6c3lmkuxwnCC:-NH6Ck-EEM5p-OXfphOp:be3ohya) ([raw file](https://github.com/tensorflow/tfjs/blob/3c79fabfcacf9cb78635de3306dcad4687e214ce/scripts/start_local_debugger_server.js#L23)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

does cloud storage allow symlink? can we have a something like
`tfjs-debugger-bundle/tfjs-debugger_latest.zip` that allows the script to use the latest build?
or should the arg parser be able to parse command line version?
</blockquote></details>

Looks like the symlink support in storage bucket is limited. I added a --version flag (with a default value) as you suggested. Thank you for the idea!


<!-- Sent from Reviewable.io -->

2022-11-22 18:08 UTC, jinjingforever commented
Hi @pyu10055 , looks like I need the approval to merge this. Thanks!

2022-11-29 17:07 UTC, pyu10055 approved these changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/7047)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @mattsoulanille)



<!-- Sent from Reviewable.io -->

2022-11-29 17:08 UTC, pyu10055 reviewed
approved, sorry for the delay.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/7047#-:-NI3M65i2wDB1_4ejRMs:b-ib2an0)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @mattsoulanille)



<!-- Sent from Reviewable.io -->

2022-12-01 19:02 UTC, merged