Fix flatten implementation on objects
tensorflow/tfjs pull request #7059
Opened 2022-11-18 01:23 UTC by ahmedsabie

Fixes #6989.

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

2022-11-21 22:17 UTC, pyu10055 requested changes
In the issue, the skipTypedArray flag seems to have been set to true?
`flatten(x, [], true)`, will your fix cover that use case?

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/7059#-:-NHRFgxXDGvSK7z1fnUw:b7jrrd2)* status: 0 of 1 approvals obtained (waiting on @ahmedsabie and @jinjingforever)

___
*[`tfjs-core/src/util_test.ts` line 183 at r1](https://reviewable.io/reviews/tensorflow/tfjs/7059#-NHR5-EyDIG7cB2if1Uk:-NHR5-EyDIG7cB2if1Ul:b-lt4wis) ([raw file](https://github.com/tensorflow/tfjs/blob/e66bc051d5388ac3765bb5da225034326d455b5c/tfjs-core/src/util_test.ts#L183)):*
> ```XML
>   });
> 
>   it('index signature', () => {
> ```

what is the use case for supporting number indexed map?


<!-- Sent from Reviewable.io -->

2022-11-24 13:21 UTC, ahmedsabie reviewed
It doesn't matter Int8Array is not part of our TypedArray definition

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/7059#-:-NHdmGMQ9vOpdsrReZts:bkdm3aq)* status: 0 of 1 approvals obtained (waiting on @jinjingforever and @pyu10055)

___
*[`tfjs-core/src/util_test.ts` line 183 at r1](https://reviewable.io/reviews/tensorflow/tfjs/7059#-NHR5-EyDIG7cB2if1Uk:-NHdmNmy99oPISrbytXI:b-g0j3rf) ([raw file](https://github.com/tensorflow/tfjs/blob/e66bc051d5388ac3765bb5da225034326d455b5c/tfjs-core/src/util_test.ts#L183)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

what is the use case for supporting number indexed map?
</blockquote></details>

Int8Array and any other fixed size buffers/arrays all fit the index signature interface but do not pass Array.isArray. 

Also it doesn't make sense to have RecursiveArray be defined as an index signature and then write a function flatten that's broken on non-array index signatures. That breaks the function type unless an error was meant to be thrown, but then RecursiveArray should not be defined as index signature.


<!-- Sent from Reviewable.io -->

2022-11-28 21:44 UTC, pyu10055 approved these changes
> #6989
thanks for the explanation

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/7059#-:-NI-Bi4kBIN3ff7C67qK:b-k60xui)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @jinjingforever)



<!-- Sent from Reviewable.io -->

2022-11-28 21:49 UTC, jinjingforever approved these changes

2022-11-29 21:14 UTC, merged