Fix tfjs-release not updating all tfjs versions of subpackages
tensorflow/tfjs pull request #7550
Opened 2023-04-05 20:41 UTC by mattsoulanille

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

2023-04-05 20:57 UTC, pyu10055 approved these changes
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/7550)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @chunnienc and @mattsoulanille)

___
*[`scripts/release-tfjs.ts` line 252 at r1](https://reviewable.io/reviews/tensorflow/tfjs/7550#-NSICNjd4G8anJdg4MB1:-NSICNje3-cG7sqwQcRS:b2qfztq) ([raw file](https://github.com/tensorflow/tfjs/blob/4ab5b7554d6f1f0f8e173d82203f6186ad4904c2/scripts/release-tfjs.ts#L252)):*
> ```XML
>         }
>         const updated = updateTFJSDependencyVersions(pkg, versions,
>                                                      depsWithPackage);
> ```

maybe use the overall version list instead of the package deps + package itself.


<!-- Sent from Reviewable.io -->

2023-04-05 21:02 UTC, pyu10055 requested changes
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/7550)* status: 0 of 1 approvals obtained (waiting on @chunnienc and @mattsoulanille)

___
*[`scripts/release-tfjs.ts` line 252 at r1](https://reviewable.io/reviews/tensorflow/tfjs/7550#-NSICNjd4G8anJdg4MB1:-NSIDXggCiA37L8FJD7Y:b-5iamvr) ([raw file](https://github.com/tensorflow/tfjs/blob/4ab5b7554d6f1f0f8e173d82203f6186ad4904c2/scripts/release-tfjs.ts#L252)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

maybe use the overall version list instead of the package deps + package itself.
</blockquote></details>

actually, throw error if the deps is beyond the package deps + package


<!-- Sent from Reviewable.io -->

2023-04-13 23:30 UTC, mattsoulanille commented
@pyu10055 I've made the script throw an error if a subpackage depends on a package that the parent package does not depend on. However, I've limited the version updating (and error reporting) to `@tensorflow`-scoped packages that are `link:` dependencies. That means demos (inside of packages) that don't use `link:` TFJS dependencies won't have those dependencies updated, which I think is more correct. We can update these demos later to use `link:` dependencies if we want them to use the latest TFJS versions, or we can remove them in favor of the tfjs-examples repo.

2023-04-18 17:28 UTC, chunnienc approved these changes
I finally understand why this fixes that issue. Good job

2023-05-17 18:40 UTC, pyu10055 approved these changes
> Reviewed 6 of 12 files at r2, 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/7550)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @mattsoulanille)

___
*[`scripts/release-util.ts` line 382 at r3](https://reviewable.io/reviews/tensorflow/tfjs/7550#-NVf-oNA5Xxt_vtr0CtK:-NVf-oNA5Xxt_vtr0CtL:b-hfpv1m) ([raw file](https://github.com/tensorflow/tfjs/blob/7da78191b4a7ba41f254dff511f55011d79fe432/scripts/release-util.ts#L382)):*
> ```XML
>   }
> 
>   // for (const dep of depsToReplace) {
> ```

remove?


<!-- Sent from Reviewable.io -->

2023-05-17 18:50 UTC, merged

2023-05-17 20:07 UTC, mattsoulanille commented
> > Reviewed 6 of 12 files at r2, 6 of 6 files at r3.
> > _[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/7550)_ status: :shipit: complete! 2 of 1 approvals obtained (waiting on @mattsoulanille)
> 
> _[`scripts/release-util.ts` line 382 at r3](https://reviewable.io/reviews/tensorflow/tfjs/7550#-NVf-oNA5Xxt_vtr0CtK:-NVf-oNA5Xxt_vtr0CtL:b-hfpv1m) ([raw file](https://github.com/tensorflow/tfjs/blob/7da78191b4a7ba41f254dff511f55011d79fe432/scripts/release-util.ts#L382)):_
> 
> > ```
> >   }
> > 
> >   // for (const dep of depsToReplace) {
> > ```
> 
> remove?

Sorry, I had auto-merge on.