Script for building the map
tensorflow/tfjs pull request #7732
Opened 2023-06-01 00:24 UTC by fengwuyao

Draft a script for build map of TFJS class and TF module path.

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

2023-06-15 00:19 UTC, Linchenn requested changes
You may also do the tests for TFCLASS_MODULE_MAP.

2023-06-15 00:19 UTC, Linchenn commented on tfjs-converter/python/tensorflowjs/converters/build_module_map.py
> +
You may delete extra newlines.

2023-06-15 00:19 UTC, Linchenn commented on tfjs-converter/python/tensorflowjs/converters/build_module_map.py
> +  _build_ts_class_module_map(path)
The RESULT_MAP might not be needed. If a class name does not exist in Keras, it should return null. If a class name does not exist in TFJS, you will not have a chance to call `get_module_path`. For both cases, TFCLASS_MODULE_MAP is enough.

2023-06-15 00:19 UTC, Linchenn commented on tfjs-converter/python/tensorflowjs/converters/build_module_map.py
> +import tensorflow.keras as keras
Add the license.

2023-06-16 17:20 UTC, Linchenn approved these changes
LGTM! Just some nits. Thanks!

2023-06-16 17:20 UTC, Linchenn commented on tfjs-converter/python/tensorflowjs/converters/tf_module_mapper.py
> +def build_map():
get_module_path and others could call _build_class_module_map directly

2023-06-16 17:20 UTC, Linchenn commented on tfjs-converter/python/tensorflowjs/converters/tf_module_mapper.py
> +# Copyright 2018 Google LLC
We could update to 2023.

2023-06-20 17:54 UTC, mattsoulanille approved these changes
LGTM

2023-06-20 17:54 UTC, merged