Github token
tensorflow/tfjs pull request #7734
Opened 2023-06-02 21:02 UTC by Dedongala

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

2023-06-02 22:38 UTC, mattsoulanille requested changes

2023-06-02 22:38 UTC, mattsoulanille commented on scripts/release_notes/release_notes.ts
> +  .trim();
Instead of reading directly from the `.bashrc`, the variable defined in the `.bashrc` should be available in node as `process.env.GITHUB_TOKEN`.

2023-06-02 22:38 UTC, mattsoulanille commented on scripts/release_notes/release_notes.ts
> -      'Enter GitHub token (https://github.com/settings/tokens): ');
We should still ask for the token if the user hasn't defined it in their `.bashrc`.

2023-06-05 18:10 UTC, Dedongala reviewed
Done

2023-06-05 18:15 UTC, mattsoulanille approved these changes
LGTM. Just a couple of nits on formatting. Thanks!

2023-06-05 18:15 UTC, mattsoulanille commented on scripts/release_notes/release_notes.ts
>        'Enter GitHub token (https://github.com/settings/tokens): ');
```suggestion

  // Getting the github token.
  let token = process.env.GITHUB_TOKEN;
  if (token == null) {
    token = await util.question(
      'Enter GitHub token (https://github.com/settings/tokens): ');
```

2023-06-05 20:09 UTC, chunnienc commented on scripts/release_notes/release_notes.ts
> + octokit.authenticate({type: 'token', token});
Use single quote `'` instead of `"`

2023-06-05 20:09 UTC, chunnienc approved these changes

2023-06-05 22:14 UTC, merged