[Draft: gpt2pre 4] GPT2Preprocessor Layer
tensorflow/tfjs pull request #7814
Opened 2023-07-10 21:13 UTC by pforderique

This PR implements the `GPT2Preprocessor` class with its `call` method.

[UPDATE]
After discussion with @mattsoulanille today, I will be making a change to the base `Layer` class too allow different input and output types to the `call` method. This will allow us to support input strings for `Tokenizers` and any other special i/o needed by the other NLP layers.

[ORIGINAL]
Here is the original plan I had, as implemented in this PR:
I had to deviate from the reference implementation a bit more here because the types can get tricky. Since GPT2Preprocessor extends the Layer class (it really extends Preprocessor, which extends Layer), its overridden call() method must return Tensor|Tensor[]. 

However, the Keras implementation allows a bit more flexibility by returning the result of pack_x_y_sample_weight(), which returns a packed tuple of x, y, and sample_weight.

Designs Considered:
* I thought about making the TS version packXYSampleWeight() simply return a Tensor of  x, y, and sample_weight so that it can be called and directly returned from call() like Keras does it, but since x is often used as an object of type {tokenIds: Tensor|Tensor[], paddingMask: Tensor[]}, this cannot be wrapped in a tensor. 
* Flattening the results into one large Tensor array is also an option, but since tokenIds will most like be a Tensor[] (since it's the result of calling tokenize() on a tensor of strings), that would mean call would have to support a return type of `Tensor|Tensor[]|(Tensor[]|Tensor)[] which starts to get confusing. Not to mention that distinguishing which output is at which position of the tensor would not be super clear.
* Create a new method callAndReturnPaddingMask that just returns a tuple of the tokenIds and paddingMask and have call return the first element (tokenIds) and ignore trying to return y and sample_weight since they aren't mutated by the class. This option is more feasible, however looking ahead, it seems that GPT2CasualLMPreprocessor class does change y and sample_weight eventually, so it's probably a good idea to figure out how to support this now.
* [DESIGN CHOSEN] I've decided to opt for making a new method callAndPackArgs that returns an array of the arguments packed similarly to the Keras version and call will simply return a subset of these outputs to keep the class layer compatible.

Since GPT2 layers always pass in x as a type of {tokenIds: Tensor|Tensor[], paddingMask: Tensor[]}, I've declared this as a PreprocessorOutput interface and removed Array checking in packXYSampleWeight.

2023-07-13 16:51 UTC, mattsoulanille requested changes
Looks good. I just have some more tests to add.

2023-07-21 20:10 UTC, mattsoulanille approved these changes
LGTM

2023-07-21 20:11 UTC, mattsoulanille commented
@Linchenn Please take a look when you get a chance. Thanks!

2023-07-21 22:16 UTC, Linchenn approved these changes
LGTM!

2023-07-21 22:52 UTC, merged